export type LanguageCode = "ru" | "en" | "et";

export const DATE_LOCALE_BY_LANGUAGE: Record<LanguageCode, string> = {
  ru: "ru-RU",
  en: "en-US",
  et: "et-EE",
};

export const DASHBOARD_TEXT = {
  ru: {
    welcome: "Добро пожаловать в Balkon",
    title: "Balkon",
    subtitle: "Discord bot dashboard для экономики, стримеров и OBS-контроля.",
    loginWithDiscord: "Войти через Discord",
    searching: "Поиск вкладок...",
    loadingSession: "Проверяем сессию...",
    loadingInventory: "Загружаем инвентарь...",
    inventoryEmpty: "Инвентарь пуст.",
    noRoles: "Ролей нет",
    discordId: "Discord ID",
    obtained: "Получено",
    tabOverview: "Обзор",
    tabInventory: "Инвентарь",
    tabMarket: "Рынок",
    tabBotShop: "Магазин",
    tabCraft: "Крафт",
    tabProfile: "Профиль",
    profile: "Профиль",
    logout: "Выйти",
    languages: "Язык",
    marketSoon: "Рынок скоро будет доступен в этой панели.",
    marketLoading: "Загружаем рынок...",
    marketEmpty: "На рынке пока нет лотов.",
    marketError: "Не удалось загрузить рынок.",
    marketPrice: "Цена",
    marketSeller: "Продавец",
    marketListingId: "Лот",
    marketInventoryItemId: "Инвентарь ID",
    marketRefresh: "Обновить",
    botShopLoading: "Загружаем магазин бота...",
    botShopEmpty: "Магазин бота пока пуст.",
    botShopError: "Не удалось загрузить магазин бота.",
    botShopPrice: "Цена",
    botShopRefresh: "Обновить",
    craftLoading: "Загружаем рецепты крафта...",
    craftEmpty: "Рецептов крафта пока нет.",
    craftError: "Не удалось загрузить рецепты крафта.",
    craftRefresh: "Обновить",
    craftResult: "Результат",
    craftIngredients: "Ингредиенты",
    craftRecipeId: "Рецепт",
    craftResultItemId: "ID результата",
    profileSection: "Профиль пользователя",
    tradeableYes: "Можно передать",
    tradeableNo: "Нельзя передать",
    sellableYes: "Можно продать",
    sellableNo: "Нельзя продать",
    botSell: "Продажа боту",
    unknownDate: "Неизвестно",
    checking: "Проверяем данные...",
    previous: "Назад",
    next: "Далее",
    page: "Страница",
    status: "Status",
    statusOnline: "Работает",
    statusOffline: "Не работает",
    statusDevelopment: "На разработке",
    inventoryFilterAll: "Все",
    inventoryFilterMaterials: "Материалы",
    inventoryFilterSellable: "Продаваемые",
    inventoryFilterTradeable: "Передаваемые",
    inventoryFilterLabel: "Фильтр инвентаря",
    itemsWord: "предметов",
    noSellableItems: "Нет продаваемых предметов.",
    noTradeableItems: "Нет передаваемых предметов.",
    noMaterialsItems: "Нет материалов.",
    adminMode: "Режим",
    adminModeUser: "Пользователь",
    adminModeAdmin: "Админ",
    adminTabDashboard: "Dashboard",
    adminTabServers: "Серверы",
    adminTabLogs: "Логи",
    adminTabObs: "OBS",
    adminTabItems: "Предметы",
    adminStatsLoading: "Загружаем админ-статистику...",
    adminStatsError: "Не удалось загрузить админ-статистику.",
    adminStatsEmpty: "Нет данных админ-статистики.",
    retry: "Повторить",
    adminCountGuilds: "Гильдии",
    adminCountMembers: "Участники",
    adminCountItems: "Предметы",
    adminCountInventory: "Инвентарь",
    adminCountMarket: "Рынок",
    adminCountStore: "Магазин",
    adminCountRecipes: "Рецепты",
    adminCountStreamers: "Стримеры",
    adminCountSettings: "Настройки",
    adminCountActions: "Действия",
    adminLogsEmpty: "Логи bootstrap пока отсутствуют.",
    statusOk: "OK",
    statusError: "Ошибка",
    source: "Источник",
    updated: "Обновлено",
    channelsSynced: "Каналы синхр.",
    rolesSynced: "Роли синхр.",
    messageLabel: "Сообщение",
    adminObsEmpty: "Настройки OBS пока отсутствуют.",
    contributors: "Contributors",
    none: "Нет",
    adminServersSoon: "Секция серверов в разработке. Здесь будет управление гильдиями, доступами и bootstrap-проверками.",
    adminItemsSoon: "Секция предметов в разработке. Здесь будет модерация каталога и контроль экономики.",
    adminItemsTitle: "Управление каталогом",
    adminItemsRefresh: "Обновить",
    adminItemsLoading: "Загружаем предметы...",
    adminItemsEmpty: "Предметы не найдены.",
    adminItemsLoadError: "Не удалось загрузить каталог предметов.",
    adminItemsSaveError: "Не удалось сохранить предмет.",
    adminItemsDeleteError: "Не удалось удалить предмет.",
    adminItemsCreated: "Предмет создан.",
    adminItemsUpdated: "Предмет обновлен.",
    adminItemsDeleted: "Предмет удален.",
    adminItemsName: "Название",
    adminItemsDescription: "Описание",
    adminItemsType: "Тип",
    adminItemsRarity: "Редкость",
    adminItemsEmoji: "Эмодзи",
    adminItemsImageUrl: "URL изображения",
    adminItemsBotSellPrice: "Цена продажи боту",
    adminItemsTradeable: "Можно передавать",
    adminItemsSearchType: "Поиск типа",
    adminItemsSearchRarity: "Поиск редкости",
    adminItemsNoOptions: "Совпадений нет",
    adminItemsCreate: "Создать",
    adminItemsUpdate: "Сохранить",
    adminItemsCancelEdit: "Отмена",
    adminItemsEdit: "Редактировать",
    adminItemsDelete: "Удалить",
    adminItemsSearchPlaceholder: "Поиск по названию, типу или редкости...",
    adminItemsValidationRequired: "Заполните обязательные поля: название, описание, тип и редкость.",
    adminItemsValidationPrice: "Цена продажи боту должна быть числом не меньше 0.",
    adminItemsDeleteConfirmTitle: "Удалить предмет",
    adminItemsDeleteConfirmText: "Вы действительно хотите удалить:",
    adminItemsDeleteConfirmAction: "Подтвердить удаление",
  },
  en: {
    welcome: "Welcome to Balkon",
    title: "Balkon",
    subtitle: "Discord bot dashboard for economy, streamers and OBS control.",
    loginWithDiscord: "Login with Discord",
    searching: "Search tabs...",
    loadingSession: "Checking session...",
    loadingInventory: "Loading inventory...",
    inventoryEmpty: "Inventory is empty.",
    noRoles: "No roles assigned",
    discordId: "Discord ID",
    obtained: "Obtained",
    tabOverview: "Overview",
    tabInventory: "Inventory",
    tabMarket: "Market",
    tabBotShop: "Bot Shop",
    tabCraft: "Craft",
    tabProfile: "Profile",
    profile: "Profile",
    logout: "Logout",
    languages: "Language",
    marketSoon: "Market section is coming soon.",
    marketLoading: "Loading market...",
    marketEmpty: "No market listings yet.",
    marketError: "Failed to load market.",
    marketPrice: "Price",
    marketSeller: "Seller",
    marketListingId: "Listing",
    marketInventoryItemId: "Inventory ID",
    marketRefresh: "Refresh",
    botShopLoading: "Loading bot shop...",
    botShopEmpty: "Bot shop is empty for now.",
    botShopError: "Failed to load bot shop.",
    botShopPrice: "Price",
    botShopRefresh: "Refresh",
    craftLoading: "Loading craft recipes...",
    craftEmpty: "No craft recipes yet.",
    craftError: "Failed to load craft recipes.",
    craftRefresh: "Refresh",
    craftResult: "Result",
    craftIngredients: "Ingredients",
    craftRecipeId: "Recipe",
    craftResultItemId: "Result ID",
    profileSection: "User profile",
    tradeableYes: "Tradeable",
    tradeableNo: "Not tradeable",
    sellableYes: "Sellable",
    sellableNo: "Not sellable",
    botSell: "Bot sell",
    unknownDate: "Unknown",
    checking: "Checking data...",
    previous: "Previous",
    next: "Next",
    page: "Page",
    status: "Status",
    statusOnline: "Online",
    statusOffline: "Offline",
    statusDevelopment: "In development",
    inventoryFilterAll: "All",
    inventoryFilterMaterials: "Materials",
    inventoryFilterSellable: "Sellable",
    inventoryFilterTradeable: "Tradeable",
    inventoryFilterLabel: "Inventory filter",
    itemsWord: "items",
    noSellableItems: "No sellable items yet.",
    noTradeableItems: "No tradeable items yet.",
    noMaterialsItems: "No materials yet.",
    adminMode: "Mode",
    adminModeUser: "User",
    adminModeAdmin: "Admin",
    adminTabDashboard: "Dashboard",
    adminTabServers: "Servers",
    adminTabLogs: "Logs",
    adminTabObs: "OBS",
    adminTabItems: "Items",
    adminStatsLoading: "Loading admin stats...",
    adminStatsError: "Failed to load admin stats.",
    adminStatsEmpty: "No admin stats available.",
    retry: "Retry",
    adminCountGuilds: "Guilds",
    adminCountMembers: "Members",
    adminCountItems: "Items",
    adminCountInventory: "Inventory",
    adminCountMarket: "Market",
    adminCountStore: "Store",
    adminCountRecipes: "Recipes",
    adminCountStreamers: "Streamers",
    adminCountSettings: "Settings",
    adminCountActions: "Actions",
    adminLogsEmpty: "No bootstrap logs yet.",
    statusOk: "OK",
    statusError: "Error",
    source: "Source",
    updated: "Updated",
    channelsSynced: "Channels synced",
    rolesSynced: "Roles synced",
    messageLabel: "Message",
    adminObsEmpty: "No OBS settings available.",
    contributors: "Contributors",
    none: "None",
    adminServersSoon: "Servers section is in progress. Guild management, access controls and bootstrap checks will appear here.",
    adminItemsSoon: "Items section is in progress. Catalog moderation and economy control tools will appear here.",
    adminItemsTitle: "Catalog Management",
    adminItemsRefresh: "Refresh",
    adminItemsLoading: "Loading items...",
    adminItemsEmpty: "No items found.",
    adminItemsLoadError: "Failed to load item catalog.",
    adminItemsSaveError: "Failed to save item.",
    adminItemsDeleteError: "Failed to delete item.",
    adminItemsCreated: "Item created.",
    adminItemsUpdated: "Item updated.",
    adminItemsDeleted: "Item deleted.",
    adminItemsName: "Name",
    adminItemsDescription: "Description",
    adminItemsType: "Type",
    adminItemsRarity: "Rarity",
    adminItemsEmoji: "Emoji",
    adminItemsImageUrl: "Image URL",
    adminItemsBotSellPrice: "Bot sell price",
    adminItemsTradeable: "Tradeable",
    adminItemsSearchType: "Search type",
    adminItemsSearchRarity: "Search rarity",
    adminItemsNoOptions: "No matches",
    adminItemsCreate: "Create",
    adminItemsUpdate: "Save",
    adminItemsCancelEdit: "Cancel",
    adminItemsEdit: "Edit",
    adminItemsDelete: "Delete",
    adminItemsSearchPlaceholder: "Search by name, type or rarity...",
    adminItemsValidationRequired: "Fill all required fields: name, description, type and rarity.",
    adminItemsValidationPrice: "Bot sell price must be a number greater or equal to 0.",
    adminItemsDeleteConfirmTitle: "Delete item",
    adminItemsDeleteConfirmText: "Do you really want to delete:",
    adminItemsDeleteConfirmAction: "Confirm delete",
  },
  et: {
    welcome: "Tere tulemast Balkonisse",
    title: "Balkon",
    subtitle: "Discordi boti juhtpaneel majanduse, striimerite ja OBS-i jaoks.",
    loginWithDiscord: "Logi sisse Discordiga",
    searching: "Otsi vahelehti...",
    loadingSession: "Sessiooni kontroll...",
    loadingInventory: "Laen inventari...",
    inventoryEmpty: "Inventar on tühi.",
    noRoles: "Rolle pole",
    discordId: "Discord ID",
    obtained: "Saadud",
    tabOverview: "Ülevaade",
    tabInventory: "Inventar",
    tabMarket: "Turg",
    tabBotShop: "Pood",
    tabCraft: "Craft",
    tabProfile: "Profiil",
    profile: "Profiil",
    logout: "Logi välja",
    languages: "Keel",
    marketSoon: "Turu vaade lisatakse peagi.",
    marketLoading: "Laen turgu...",
    marketEmpty: "Turul pole veel pakkumisi.",
    marketError: "Turu laadimine ebaõnnestus.",
    marketPrice: "Hind",
    marketSeller: "Müüja",
    marketListingId: "Pakkumine",
    marketInventoryItemId: "Inventari ID",
    marketRefresh: "Värskenda",
    botShopLoading: "Laen botipoodi...",
    botShopEmpty: "Botipood on praegu tühi.",
    botShopError: "Botipoe laadimine ebaõnnestus.",
    botShopPrice: "Hind",
    botShopRefresh: "Värskenda",
    craftLoading: "Laen crafti retsepte...",
    craftEmpty: "Crafti retsepte veel pole.",
    craftError: "Crafti retseptide laadimine ebaõnnestus.",
    craftRefresh: "Värskenda",
    craftResult: "Tulemus",
    craftIngredients: "Koostisosad",
    craftRecipeId: "Retsept",
    craftResultItemId: "Tulemuse ID",
    profileSection: "Kasutaja profiil",
    tradeableYes: "Vahetatav",
    tradeableNo: "Ei ole vahetatav",
    sellableYes: "Müüdav",
    sellableNo: "Ei ole müüdav",
    botSell: "Botile müük",
    unknownDate: "Teadmata",
    checking: "Andmete kontroll...",
    previous: "Eelmine",
    next: "Järgmine",
    page: "Leht",
    status: "Status",
    statusOnline: "Töötab",
    statusOffline: "Ei tööta",
    statusDevelopment: "Arenduses",
    inventoryFilterAll: "Kõik",
    inventoryFilterMaterials: "Materjalid",
    inventoryFilterSellable: "Müüdavad",
    inventoryFilterTradeable: "Vahetatavad",
    inventoryFilterLabel: "Inventari filter",
    itemsWord: "eset",
    noSellableItems: "Müüdavaid esemeid veel pole.",
    noTradeableItems: "Vahetatavaid esemeid veel pole.",
    noMaterialsItems: "Materjale veel pole.",
    adminMode: "Režiim",
    adminModeUser: "Kasutaja",
    adminModeAdmin: "Admin",
    adminTabDashboard: "Dashboard",
    adminTabServers: "Serverid",
    adminTabLogs: "Logid",
    adminTabObs: "OBS",
    adminTabItems: "Esemed",
    adminStatsLoading: "Laen admin-statistikat...",
    adminStatsError: "Admin-statistika laadimine ebaõnnestus.",
    adminStatsEmpty: "Admin-statistika puudub.",
    retry: "Proovi uuesti",
    adminCountGuilds: "Guildid",
    adminCountMembers: "Liikmed",
    adminCountItems: "Esemed",
    adminCountInventory: "Inventar",
    adminCountMarket: "Turg",
    adminCountStore: "Pood",
    adminCountRecipes: "Retseptid",
    adminCountStreamers: "Striimerid",
    adminCountSettings: "Seaded",
    adminCountActions: "Tegevused",
    adminLogsEmpty: "Bootstrap-logisid veel pole.",
    statusOk: "OK",
    statusError: "Viga",
    source: "Allikas",
    updated: "Uuendatud",
    channelsSynced: "Kanalid sünk",
    rolesSynced: "Rollid sünk",
    messageLabel: "Sõnum",
    adminObsEmpty: "OBS seaded puuduvad.",
    contributors: "Contributors",
    none: "Puudub",
    adminServersSoon: "Serverite sektsioon on arenduses. Siia tulevad guildide haldus, juurdepääsud ja bootstrap kontrollid.",
    adminItemsSoon: "Esemete sektsioon on arenduses. Siia tulevad kataloogi haldus ja economy kontroll.",
    adminItemsTitle: "Kataloogi haldus",
    adminItemsRefresh: "Värskenda",
    adminItemsLoading: "Laen esemeid...",
    adminItemsEmpty: "Esemeid ei leitud.",
    adminItemsLoadError: "Esemete kataloogi laadimine ebaõnnestus.",
    adminItemsSaveError: "Esme salvestamine ebaõnnestus.",
    adminItemsDeleteError: "Esme kustutamine ebaõnnestus.",
    adminItemsCreated: "Ese loodud.",
    adminItemsUpdated: "Ese uuendatud.",
    adminItemsDeleted: "Ese kustutatud.",
    adminItemsName: "Nimi",
    adminItemsDescription: "Kirjeldus",
    adminItemsType: "Tüüp",
    adminItemsRarity: "Haruldus",
    adminItemsEmoji: "Emoji",
    adminItemsImageUrl: "Pildi URL",
    adminItemsBotSellPrice: "Botile müügihind",
    adminItemsTradeable: "Vahetatav",
    adminItemsSearchType: "Otsi tüüpi",
    adminItemsSearchRarity: "Otsi haruldust",
    adminItemsNoOptions: "Vasteid pole",
    adminItemsCreate: "Loo",
    adminItemsUpdate: "Salvesta",
    adminItemsCancelEdit: "Tühista",
    adminItemsEdit: "Muuda",
    adminItemsDelete: "Kustuta",
    adminItemsSearchPlaceholder: "Otsi nime, tüübi või harulduse järgi...",
    adminItemsValidationRequired: "Täida kohustuslikud väljad: nimi, kirjeldus, tüüp ja haruldus.",
    adminItemsValidationPrice: "Botile müügihind peab olema arv, mis on 0 või suurem.",
    adminItemsDeleteConfirmTitle: "Kustuta ese",
    adminItemsDeleteConfirmText: "Kas soovid kindlasti kustutada:",
    adminItemsDeleteConfirmAction: "Kinnita kustutamine",
  },
} as const;

export type DashboardText = (typeof DASHBOARD_TEXT)[LanguageCode];

export function formatDashboardDate(value: string | Date | null | undefined, locale: string, unknownDate: string): string {
  if (value === null || value === undefined) {
    return unknownDate;
  }

  const date = new Date(String(value));
  if (Number.isNaN(date.getTime())) {
    return unknownDate;
  }

  return new Intl.DateTimeFormat(locale, {
    year: "numeric",
    month: "short",
    day: "2-digit",
  }).format(date);
}
