export type LanguageCode = "ru" | "en" | "et";

export const DATE_LOCALE_BY_LANGUAGE: Record<LanguageCode, string> = {
  ru: "ru-RU",
  en: "en-US",
  et: "et-EE",
};

export const DASHBOARD_TEXT = {
  ru: {
    welcome: "Добро пожаловать в Balkon",
    title: "Balkon",
    subtitle: "Discord bot dashboard для экономики, стримеров и OBS-контроля.",
    loginWithDiscord: "Войти через Discord",
    searching: "Поиск вкладок...",
    loadingSession: "Проверяем сессию...",
    loadingInventory: "Загружаем инвентарь...",
    inventoryEmpty: "Инвентарь пуст.",
    noRoles: "Ролей нет",
    discordId: "Discord ID",
    obtained: "Получено",
    tabOverview: "Обзор",
    tabInventory: "Инвентарь",
    tabMarket: "Рынок",
    tabProfile: "Профиль",
    profile: "Профиль",
    logout: "Выйти",
    languages: "Язык",
    marketSoon: "Рынок скоро будет доступен в этой панели.",
    marketLoading: "Загружаем рынок...",
    marketEmpty: "На рынке пока нет лотов.",
    marketError: "Не удалось загрузить рынок.",
    marketPrice: "Цена",
    marketSeller: "Продавец",
    marketListingId: "Лот",
    marketInventoryItemId: "Инвентарь ID",
    marketRefresh: "Обновить",
    profileSection: "Профиль пользователя",
    tradeableYes: "Можно передать",
    tradeableNo: "Нельзя передать",
    sellableYes: "Можно продать",
    sellableNo: "Нельзя продать",
    botSell: "Продажа боту",
    unknownDate: "Неизвестно",
    checking: "Проверяем данные...",
    previous: "Назад",
    next: "Далее",
    page: "Страница",
    status: "Status",
    statusOnline: "Работает",
    statusOffline: "Не работает",
    statusDevelopment: "На разработке",
    inventoryFilterAll: "Все",
    inventoryFilterMaterials: "Материалы",
    inventoryFilterSellable: "Продаваемые",
    inventoryFilterTradeable: "Передаваемые",
    inventoryFilterLabel: "Фильтр инвентаря",
    itemsWord: "предметов",
    noSellableItems: "Нет продаваемых предметов.",
    noTradeableItems: "Нет передаваемых предметов.",
    noMaterialsItems: "Нет материалов.",
    adminMode: "Режим",
    adminModeUser: "Пользователь",
    adminModeAdmin: "Админ",
    adminTabDashboard: "Dashboard",
    adminTabServers: "Серверы",
    adminTabLogs: "Логи",
    adminTabObs: "OBS",
    adminTabItems: "Предметы",
    adminStatsLoading: "Загружаем админ-статистику...",
    adminStatsError: "Не удалось загрузить админ-статистику.",
    adminStatsEmpty: "Нет данных админ-статистики.",
    retry: "Повторить",
    adminCountGuilds: "Гильдии",
    adminCountMembers: "Участники",
    adminCountItems: "Предметы",
    adminCountInventory: "Инвентарь",
    adminCountMarket: "Рынок",
    adminCountStore: "Магазин",
    adminCountRecipes: "Рецепты",
    adminCountStreamers: "Стримеры",
    adminCountSettings: "Настройки",
    adminCountActions: "Действия",
    adminLogsEmpty: "Логи bootstrap пока отсутствуют.",
    statusOk: "OK",
    statusError: "Ошибка",
    source: "Источник",
    updated: "Обновлено",
    channelsSynced: "Каналы синхр.",
    rolesSynced: "Роли синхр.",
    messageLabel: "Сообщение",
    adminObsEmpty: "Настройки OBS пока отсутствуют.",
    contributors: "Contributors",
    none: "Нет",
    adminServersSoon: "Секция серверов в разработке. Здесь будет управление гильдиями, доступами и bootstrap-проверками.",
    adminItemsSoon: "Секция предметов в разработке. Здесь будет модерация каталога и контроль экономики.",
  },
  en: {
    welcome: "Welcome to Balkon",
    title: "Balkon",
    subtitle: "Discord bot dashboard for economy, streamers and OBS control.",
    loginWithDiscord: "Login with Discord",
    searching: "Search tabs...",
    loadingSession: "Checking session...",
    loadingInventory: "Loading inventory...",
    inventoryEmpty: "Inventory is empty.",
    noRoles: "No roles assigned",
    discordId: "Discord ID",
    obtained: "Obtained",
    tabOverview: "Overview",
    tabInventory: "Inventory",
    tabMarket: "Market",
    tabProfile: "Profile",
    profile: "Profile",
    logout: "Logout",
    languages: "Language",
    marketSoon: "Market section is coming soon.",
    marketLoading: "Loading market...",
    marketEmpty: "No market listings yet.",
    marketError: "Failed to load market.",
    marketPrice: "Price",
    marketSeller: "Seller",
    marketListingId: "Listing",
    marketInventoryItemId: "Inventory ID",
    marketRefresh: "Refresh",
    profileSection: "User profile",
    tradeableYes: "Tradeable",
    tradeableNo: "Not tradeable",
    sellableYes: "Sellable",
    sellableNo: "Not sellable",
    botSell: "Bot sell",
    unknownDate: "Unknown",
    checking: "Checking data...",
    previous: "Previous",
    next: "Next",
    page: "Page",
    status: "Status",
    statusOnline: "Online",
    statusOffline: "Offline",
    statusDevelopment: "In development",
    inventoryFilterAll: "All",
    inventoryFilterMaterials: "Materials",
    inventoryFilterSellable: "Sellable",
    inventoryFilterTradeable: "Tradeable",
    inventoryFilterLabel: "Inventory filter",
    itemsWord: "items",
    noSellableItems: "No sellable items yet.",
    noTradeableItems: "No tradeable items yet.",
    noMaterialsItems: "No materials yet.",
    adminMode: "Mode",
    adminModeUser: "User",
    adminModeAdmin: "Admin",
    adminTabDashboard: "Dashboard",
    adminTabServers: "Servers",
    adminTabLogs: "Logs",
    adminTabObs: "OBS",
    adminTabItems: "Items",
    adminStatsLoading: "Loading admin stats...",
    adminStatsError: "Failed to load admin stats.",
    adminStatsEmpty: "No admin stats available.",
    retry: "Retry",
    adminCountGuilds: "Guilds",
    adminCountMembers: "Members",
    adminCountItems: "Items",
    adminCountInventory: "Inventory",
    adminCountMarket: "Market",
    adminCountStore: "Store",
    adminCountRecipes: "Recipes",
    adminCountStreamers: "Streamers",
    adminCountSettings: "Settings",
    adminCountActions: "Actions",
    adminLogsEmpty: "No bootstrap logs yet.",
    statusOk: "OK",
    statusError: "Error",
    source: "Source",
    updated: "Updated",
    channelsSynced: "Channels synced",
    rolesSynced: "Roles synced",
    messageLabel: "Message",
    adminObsEmpty: "No OBS settings available.",
    contributors: "Contributors",
    none: "None",
    adminServersSoon: "Servers section is in progress. Guild management, access controls and bootstrap checks will appear here.",
    adminItemsSoon: "Items section is in progress. Catalog moderation and economy control tools will appear here.",
  },
  et: {
    welcome: "Tere tulemast Balkonisse",
    title: "Balkon",
    subtitle: "Discordi boti juhtpaneel majanduse, striimerite ja OBS-i jaoks.",
    loginWithDiscord: "Logi sisse Discordiga",
    searching: "Otsi vahelehti...",
    loadingSession: "Sessiooni kontroll...",
    loadingInventory: "Laen inventari...",
    inventoryEmpty: "Inventar on tühi.",
    noRoles: "Rolle pole",
    discordId: "Discord ID",
    obtained: "Saadud",
    tabOverview: "Ülevaade",
    tabInventory: "Inventar",
    tabMarket: "Turg",
    tabProfile: "Profiil",
    profile: "Profiil",
    logout: "Logi välja",
    languages: "Keel",
    marketSoon: "Turu vaade lisatakse peagi.",
    marketLoading: "Laen turgu...",
    marketEmpty: "Turul pole veel pakkumisi.",
    marketError: "Turu laadimine ebaõnnestus.",
    marketPrice: "Hind",
    marketSeller: "Müüja",
    marketListingId: "Pakkumine",
    marketInventoryItemId: "Inventari ID",
    marketRefresh: "Värskenda",
    profileSection: "Kasutaja profiil",
    tradeableYes: "Vahetatav",
    tradeableNo: "Ei ole vahetatav",
    sellableYes: "Müüdav",
    sellableNo: "Ei ole müüdav",
    botSell: "Botile müük",
    unknownDate: "Teadmata",
    checking: "Andmete kontroll...",
    previous: "Eelmine",
    next: "Järgmine",
    page: "Leht",
    status: "Status",
    statusOnline: "Töötab",
    statusOffline: "Ei tööta",
    statusDevelopment: "Arenduses",
    inventoryFilterAll: "Kõik",
    inventoryFilterMaterials: "Materjalid",
    inventoryFilterSellable: "Müüdavad",
    inventoryFilterTradeable: "Vahetatavad",
    inventoryFilterLabel: "Inventari filter",
    itemsWord: "eset",
    noSellableItems: "Müüdavaid esemeid veel pole.",
    noTradeableItems: "Vahetatavaid esemeid veel pole.",
    noMaterialsItems: "Materjale veel pole.",
    adminMode: "Režiim",
    adminModeUser: "Kasutaja",
    adminModeAdmin: "Admin",
    adminTabDashboard: "Dashboard",
    adminTabServers: "Serverid",
    adminTabLogs: "Logid",
    adminTabObs: "OBS",
    adminTabItems: "Esemed",
    adminStatsLoading: "Laen admin-statistikat...",
    adminStatsError: "Admin-statistika laadimine ebaõnnestus.",
    adminStatsEmpty: "Admin-statistika puudub.",
    retry: "Proovi uuesti",
    adminCountGuilds: "Guildid",
    adminCountMembers: "Liikmed",
    adminCountItems: "Esemed",
    adminCountInventory: "Inventar",
    adminCountMarket: "Turg",
    adminCountStore: "Pood",
    adminCountRecipes: "Retseptid",
    adminCountStreamers: "Striimerid",
    adminCountSettings: "Seaded",
    adminCountActions: "Tegevused",
    adminLogsEmpty: "Bootstrap-logisid veel pole.",
    statusOk: "OK",
    statusError: "Viga",
    source: "Allikas",
    updated: "Uuendatud",
    channelsSynced: "Kanalid sünk",
    rolesSynced: "Rollid sünk",
    messageLabel: "Sõnum",
    adminObsEmpty: "OBS seaded puuduvad.",
    contributors: "Contributors",
    none: "Puudub",
    adminServersSoon: "Serverite sektsioon on arenduses. Siia tulevad guildide haldus, juurdepääsud ja bootstrap kontrollid.",
    adminItemsSoon: "Esemete sektsioon on arenduses. Siia tulevad kataloogi haldus ja economy kontroll.",
  },
} as const;

export type DashboardText = (typeof DASHBOARD_TEXT)[LanguageCode];

export function formatDashboardDate(value: string | Date | null | undefined, locale: string, unknownDate: string): string {
  if (value === null || value === undefined) {
    return unknownDate;
  }

  const date = new Date(String(value));
  if (Number.isNaN(date.getTime())) {
    return unknownDate;
  }

  return new Intl.DateTimeFormat(locale, {
    year: "numeric",
    month: "short",
    day: "2-digit",
  }).format(date);
}
