export type LanguageCode = "ru" | "en" | "et";

export const DATE_LOCALE_BY_LANGUAGE: Record<LanguageCode, string> = {
  ru: "ru-RU",
  en: "en-US",
  et: "et-EE",
};

export const DASHBOARD_TEXT = {
  ru: {
    welcome: "Добро пожаловать в Balkon",
    title: "Balkon",
    subtitle: "Discord bot dashboard для экономики, стримеров и OBS-контроля.",
    loginWithDiscord: "Войти через Discord",
    searching: "Поиск вкладок...",
    marketOverviewSearchDescription: "Капитализация, график ODM",
    marketListingsSearchDescription: "Предметы игроков на продаже",
    marketForbesSearchDescription: "Топ 10 пользователей по ODM",
    botShopSearchDescription: "Покупка у бота",
    inventorySearchDescription: "Ваши предметы, продажа и передача",
    craftSearchDescription: "Рецепты и создание предметов",
    profileSearchDescription: "Аккаунт и Discord профиль",
    loadingSession: "Проверяем сессию...",
    loadingInventory: "Загружаем инвентарь...",
    inventoryEmpty: "Инвентарь пуст.",
    noRoles: "Ролей нет",
    discordId: "Discord ID",
    obtained: "Получено",
    itemDetails: "Детали предмета",
    close: "Закрыть",
    itemId: "ID предмета",
    templateId: "ID шаблона",
    owner: "Владелец",
    originalOwner: "Исходный владелец",
    rarity: "Редкость",
    type: "Тип",
    tier: "Тир",
    botSellPrice: "Цена продажи боту",
    noItemSelected: "Предмет не выбран.",
    selectItemHint: "Выберите предмет слева, чтобы увидеть подробности.",
    tabOverview: "Обзор",
    tabInventory: "Инвентарь",
    tabMarket: "Рынок",
    tabBotShop: "Магазин",
    tabCraft: "Крафт",
    tabProfile: "Профиль",
    tabNotifications: "Уведомления",
    tabServers: "Серверы",
    tabStreamerStudio: "Стримерская",
    navMain: "Главное",
    navPersonal: "Личное",
    navEconomy: "Экономика",
    navObs: "Стримы",
    navServers: "Серверы",
    navAdmin: "Админка",
    myServers: "Мои серверы",
    serversComingSoon: "Скоро",
    serverManagementDescription: "Скоро здесь можно будет выбрать Discord сервер и управлять экономикой, участниками и настройками.",
    serversTitle: "Мои серверы",
    serversSubtitle: "Выберите зарегистрированный Discord сервер, чтобы посмотреть обзор и подготовить управление.",
    serversEmpty: "Зарегистрированных серверов пока нет.",
    serversError: "Не удалось загрузить серверы.",
    serversRefresh: "Обновить",
    openServer: "Открыть",
    backToServers: "К серверам",
    serverRoleOwner: "Владелец",
    serverRoleAdmin: "Админ",
    serverRoleMember: "Участник",
    serverRoleUnknown: "Неизвестно",
    serverHomeGuild: "Домашний",
    serverMembers: "Участники",
    serverStreamers: "Стримеры",
    serverItems: "Предметы",
    serverInventory: "Инвентарь",
    serverMarketListings: "Рынок",
    serverTabOverview: "Обзор",
    serverTabEconomy: "Экономика",
    serverTabMembers: "Участники",
    serverTabLogs: "Логи",
    serverTabSettings: "Настройки",
    serverSectionComingSoon: "Скоро здесь появится управление этим разделом.",
    obsShop: "OBS магазин",
    obsHistory: "OBS история",
    streamerStudioTitle: "Стримерская",
    streamerStudioSubtitle: "Управляйте сценами OBS и размещением элементов через браузер.",
    streamerStudioRefresh: "Обновить",
    streamerStudioEmpty: "Нет доступных стримеров.",
    streamerStudioError: "Не удалось загрузить Стримерскую.",
    streamerStudioOpenControl: "Открыть контроль",
    streamerStudioBack: "Назад",
    streamerStudioRoleOwner: "Владелец",
    streamerStudioRoleManager: "Менеджер",
    streamerStudioRoleModerator: "Модератор",
    streamerStudioRoleBotAdmin: "Bot admin",
    streamerStudioCanControl: "Можно управлять",
    streamerStudioCanManage: "Можно настраивать доступ",
    streamerStudioAgentOnline: "OBS агент онлайн",
    streamerStudioAgentOffline: "OBS агент оффлайн",
    streamerStudioAgentNotConfigured: "OBS агент не настроен",
    streamerStudioAgentVersionLabel: "Версия агента",
    streamerStudioRelayProtocolLabel: "Версия relay protocol",
    streamerStudioCapabilitiesLabel: "Команды",
    streamerStudioObsStatusLabel: "OBS",
    streamerStudioObsConnected: "подключён",
    streamerStudioObsDisconnected: "не подключён",
    streamerStudioObsVersionLabel: "Версия OBS",
    streamerStudioObsWebsocketVersionLabel: "Версия obs-websocket",
    streamerStudioCapabilitiesUnknown: "Возможности OBS Agent неизвестны. Если расширенные действия не работают, обновите и перезапустите агент.",
    streamerStudioCapabilityUnsupported: "OBS Agent устарел или не поддерживает эту команду. Обновите и перезапустите агент.",
    streamerStudioObsNotConnected: "OBS не подключён. Откройте OBS и переподключите агент.",
    streamerStudioScenes: "Сцены",
    streamerStudioLoadScenes: "Загрузить сцены",
    streamerStudioRefreshScenes: "Обновить сцены",
    streamerStudioRefreshItems: "Обновить элементы",
    streamerStudioLoadingScenes: "Загружаем сцены...",
    streamerStudioLoadingItems: "Загружаем элементы сцены...",
    streamerStudioSceneItems: "Объекты сцены",
    streamerStudioNoScenes: "Сцен нет",
    streamerStudioNoItems: "Объектов нет",
    streamerStudioSelectScene: "Выберите сцену",
    streamerStudioPreview: "Превью",
    streamerStudioInspector: "Инспектор",
    streamerStudioUnknownInput: "unknown",
    streamerStudioTypeGroup: "group",
    streamerStudioRecommended: "Рекомендуется",
    streamerStudioEnabled: "Включено",
    streamerStudioDisabled: "Выключено",
    streamerStudioApplyTransform: "Применить в OBS",
    streamerStudioResetTransform: "Сбросить изменения",
    streamerStudioUnsavedChanges: "Есть несохранённые изменения",
    streamerStudioTransformApplied: "Позиция применена",
    streamerStudioTransformApplyFailed: "Не удалось применить позицию",
    streamerStudioLayerControlsTitle: "Слой",
    streamerStudioMoveLayerUp: "Выше",
    streamerStudioMoveLayerDown: "Ниже",
    streamerStudioMoveLayerTop: "В самый верх",
    streamerStudioMoveLayerBottom: "В самый низ",
    streamerStudioLayerApplied: "Порядок обновлён",
    streamerStudioLayerApplyFailed: "Не удалось изменить порядок",
    streamerStudioVisibilityControlsTitle: "Видимость",
    streamerStudioShowItem: "Показать",
    streamerStudioHideItem: "Скрыть",
    streamerStudioRemoveItem: "Удалить",
    streamerStudioVisibilityApplied: "Видимость обновлена",
    streamerStudioVisibilityApplyFailed: "Не удалось изменить видимость",
    streamerStudioRemoveApplied: "Элемент удалён из сцены",
    streamerStudioRemoveFailed: "Не удалось удалить элемент",
    streamerStudioRemoveConfirm: "Удалить элемент из текущей OBS-сцены?",
    streamerStudioRemoveHint: "Удаляет элемент только из текущей сцены.",
    streamerStudioTransformX: "X",
    streamerStudioTransformY: "Y",
    streamerStudioTransformScaleX: "Масштаб X",
    streamerStudioTransformScaleY: "Масштаб Y",
    streamerStudioTransformRotation: "Поворот",
    streamerStudioDragHint: "Перетащите выбранный элемент или измените значения вручную",
    streamerStudioLayerOrderHint: "Порядок как в OBS: верхние элементы отображаются поверх нижних.",
    streamerStudioDirtyRefreshConfirm: "Есть несохранённые изменения. Обновить элементы и сбросить их?",
    streamerStudioForbiddenHint: "Нет доступа к управлению этим стримером.",
    streamerStudioCreateSourceTitle: "Создать источник",
    streamerStudioCreateTextTitle: "Текст",
    streamerStudioCreateTextSubtitle: "Добавьте текстовый источник в выбранную OBS-сцену.",
    streamerStudioCreateTextContent: "Текст",
    streamerStudioCreateTextSourceName: "Название источника",
    streamerStudioCreateTextSourceNamePlaceholder: "Например: Balkon Text",
    streamerStudioCreateTextButton: "Добавить текст",
    streamerStudioCreateTextSuccess: "Текстовый источник создан",
    streamerStudioCreateTextFailed: "Не удалось создать текстовый источник",
    streamerStudioCreateTextInvalid: "Введите текст до 500 символов.",
    streamerStudioCreateTextOpen: "Открыть",
    streamerStudioCreateTextCollapse: "Свернуть",
    streamerStudioSourceSettingsTitle: "Настройки источника",
    streamerStudioSourceSettingsLoading: "Загружаем настройки источника...",
    streamerStudioSourceSettingsLoadFailed: "Не удалось загрузить настройки источника",
    streamerStudioTextSettingsTitle: "Текст",
    streamerStudioTextSettingsContent: "Содержимое",
    streamerStudioTextSettingsPlaceholder: "Введите новый текст для источника",
    streamerStudioTextSettingsUpdate: "Обновить текст",
    streamerStudioTextSettingsSuccess: "Текст источника обновлён",
    streamerStudioTextSettingsFailed: "Не удалось обновить текст источника",
    streamerStudioTextSettingsInvalid: "Введите текст от 1 до 500 символов.",
    streamerStudioCreateBrowserTitle: "Browser URL",
    streamerStudioCreateBrowserSubtitle: "Добавьте browser source по ссылке в выбранную OBS-сцену.",
    streamerStudioCreateBrowserUrl: "URL",
    streamerStudioCreateBrowserUrlPlaceholder: "https://example.com/widget",
    streamerStudioCreateBrowserWidth: "Ширина",
    streamerStudioCreateBrowserHeight: "Высота",
    streamerStudioCreateBrowserButton: "Добавить Browser",
    streamerStudioCreateBrowserSuccess: "Browser source создан",
    streamerStudioCreateBrowserFailed: "Не удалось создать Browser source",
    streamerStudioCreateBrowserInvalid: "Введите корректный http/https URL.",
    streamerStudioBrowserSettingsTitle: "Browser source",
    streamerStudioBrowserSettingsUrl: "URL",
    streamerStudioBrowserSettingsUrlPlaceholder: "https://example.com/widget",
    streamerStudioBrowserSettingsWidth: "Ширина",
    streamerStudioBrowserSettingsHeight: "Высота",
    streamerStudioBrowserSettingsUpdate: "Обновить Browser",
    streamerStudioBrowserSettingsSuccess: "Browser source обновлён",
    streamerStudioBrowserSettingsFailed: "Не удалось обновить Browser source",
    streamerStudioBrowserSettingsInvalid: "Укажите хотя бы одно поле и используйте корректный http/https URL.",
    streamerStudioCreateSourceTypeText: "Текст",
    streamerStudioCreateSourceTypeBrowser: "Browser",
    streamerStudioTrustedUsersTitle: "Доверенные пользователи",
    streamerStudioTrustedUsersSubtitle: "Добавьте людей, которым можно бесплатно управлять вашей OBS-сценой.",
    streamerStudioTrustedUsersRefresh: "Обновить",
    streamerStudioTrustedUsersOpen: "Открыть",
    streamerStudioTrustedUsersCollapse: "Свернуть",
    streamerStudioTrustedUsersCount: "{count} доверенных",
    streamerStudioTrustedUsersEmpty: "Доверенных пользователей пока нет.",
    streamerStudioTrustedUsersDiscordId: "Discord ID",
    streamerStudioTrustedUsersRole: "Роль",
    streamerStudioTrustedUsersAdd: "Добавить",
    streamerStudioTrustedUsersRemove: "Удалить",
    streamerStudioTrustedUsersModerator: "Модератор",
    streamerStudioTrustedUsersManager: "Менеджер",
    streamerStudioTrustedUsersAddSuccess: "Пользователь добавлен",
    streamerStudioTrustedUsersRemoveSuccess: "Доступ удалён",
    streamerStudioTrustedUsersLoadFailed: "Не удалось загрузить доверенных пользователей",
    streamerStudioTrustedUsersSaveFailed: "Не удалось сохранить доступ",
    streamerStudioTrustedUsersDeleteFailed: "Не удалось удалить доступ",
    streamerStudioTrustedUsersInvalidDiscordId: "Discord ID должен содержать только цифры и быть не длиннее 32 символов.",
    streamerStudioTrustedUsersManagerHint: "Менеджер может управлять сценой и списком доверенных пользователей.",
    streamerStudioAgentSetupTitle: "Настройка OBS Agent",
    streamerStudioAgentSetupSubtitle: "Подключите локальный Balkon OBS Agent для браузерного управления сценами и источниками.",
    streamerStudioAgentSetupRefresh: "Обновить статус",
    streamerStudioAgentSetupConfigured: "Связка настроена",
    streamerStudioAgentSetupNotConfigured: "Связка не настроена",
    streamerStudioAgentSetupReady: "Агент готов",
    streamerStudioAgentSetupOfflineHint: "OBS Agent оффлайн",
    streamerStudioAgentSetupObsDisconnectedHint: "OBS не подключён. Откройте OBS и переподключите агент.",
    streamerStudioAgentSetupTokenPresent: "Токен сохранён",
    streamerStudioAgentSetupTokenMissing: "Токен отсутствует",
    streamerStudioAgentSetupLastSeen: "Последняя связь",
    streamerStudioAgentSetupUnknown: "Неизвестно",
    streamerStudioAgentSetupTabStatus: "Статус",
    streamerStudioAgentSetupTabSetup: "Подключение",
    streamerStudioAgentSetupTabToken: "Токен",
    streamerStudioAgentSetupTabManualBind: "Привязать вручную",
    streamerStudioAgentSetupTabDanger: "Опасно",
    streamerStudioAgentSetupInstructionsTitle: "Как подключить агент",
    streamerStudioAgentSetupInstructionInstall: "1. Установите или откройте Balkon OBS Agent на ПК стримера.",
    streamerStudioAgentSetupInstructionRelay: "2. Укажите Relay URL.",
    streamerStudioAgentSetupInstructionAgentId: "3. Укажите Agent ID.",
    streamerStudioAgentSetupInstructionAgentToken: "4. Укажите Agent Token.",
    streamerStudioAgentSetupInstructionObs: "5. Укажите OBS WebSocket URL и пароль в агенте.",
    streamerStudioAgentSetupInstructionStart: "6. Запустите агент и дождитесь подключения.",
    streamerStudioAgentSetupRelayUnavailable: "Relay URL пока не публикуется backend'ом. Используйте relay URL вашего деплоя из конфигурации.",
    streamerStudioAgentSetupRelayLabel: "Relay URL",
    streamerStudioAgentSetupAgentIdLabel: "Agent ID",
    streamerStudioAgentSetupTokenLabel: "Agent Token",
    streamerStudioAgentSetupCustomAgentId: "Кастомный Agent ID",
    streamerStudioAgentSetupCustomAgentIdPlaceholder: "Оставьте пустым для автогенерации",
    streamerStudioAgentSetupGenerateToken: "Сгенерировать / ротировать токен",
    streamerStudioAgentSetupGenerating: "Генерируем токен...",
    streamerStudioAgentSetupCopy: "Копировать",
    streamerStudioAgentSetupCopied: "Скопировано",
    streamerStudioAgentSetupCopyFailed: "Не удалось скопировать",
    streamerStudioAgentSetupOneTimeTitle: "Новый токен",
    streamerStudioAgentSetupOneTimeWarning: "Скопируйте этот токен сейчас. Он больше не будет показан.",
    streamerStudioAgentSetupCopyNowWarning: "Скопируйте токен сейчас. После закрытия он больше не будет показан.",
    streamerStudioAgentSetupBindTitle: "Привязать вручную",
    streamerStudioAgentSetupBindSubtitle: "Используйте, если у вас уже есть Agent ID и Agent Token.",
    streamerStudioAgentSetupBindButton: "Сохранить привязку",
    streamerStudioAgentSetupBinding: "Сохраняем...",
    streamerStudioAgentSetupBindSuccess: "Привязка сохранена",
    streamerStudioAgentSetupBindFailed: "Не удалось сохранить привязку",
    streamerStudioAgentSetupProvisionSuccess: "Новый токен сгенерирован",
    streamerStudioAgentSetupProvisionFailed: "Не удалось сгенерировать токен",
    streamerStudioAgentSetupClear: "Очистить привязку",
    streamerStudioAgentSetupClearing: "Очищаем...",
    streamerStudioAgentSetupClearSuccess: "Привязка удалена",
    streamerStudioAgentSetupClearFailed: "Не удалось удалить привязку",
    streamerStudioAgentSetupClearConfirm: "Удалить текущую привязку OBS Agent для этого стримера?",
    streamerStudioAgentSetupClearWarning: "Это удалит текущую привязку OBS Agent для стримера. Понадобится повторная настройка или новая привязка.",
    streamerStudioAgentSetupInvalidBind: "Укажите Agent ID и Agent Token.",
    configure: "Настроить",
    quickActions: "Быстрые действия",
    recentActivity: "Последняя активность",
    overviewNotLoaded: "Не загружено",
    overviewOpenInventory: "Открыть инвентарь",
    overviewProfileHint: "Настройте домашний сервер и публичное описание.",
    overviewRecentEmpty: "Пока нет свежей активности.",
    overviewLoadFailed: "Не удалось загрузить обзор.",
    overviewShowcaseEyebrow: "Витрина",
    overviewShowcaseTitle: "Балкон витрина",
    overviewShowcaseSubtitle: "Здесь будет 3D-витрина предметов, эффектов и событий Balkon.",
    overviewModelSoon: "3D модель скоро появится",
    profile: "Профиль",
    logout: "Выйти",
    balance: "Баланс",
    odm: "ODM",
    ldm: "LDM",
    balanceLoadFailed: "Не удалось загрузить баланс.",
    buy: "Купить",
    buying: "Покупка...",
    amount: "Количество",
    total: "Итого",
    notEnoughBalance: "Недостаточно ODM.",
    purchaseSuccess: "Куплено!",
    purchaseFailed: "Ошибка покупки.",
    languages: "Язык",
    marketSoon: "Рынок скоро будет доступен в этой панели.",
    marketLoading: "Загружаем рынок...",
    marketEmpty: "На рынке пока нет лотов.",
    marketError: "Не удалось загрузить рынок.",
    marketPrice: "Цена",
    marketSeller: "Продавец",
    marketListingId: "Лот",
    marketInventoryItemId: "Инвентарь ID",
    marketOverview: "Обзор",
    marketListings: "Предметы",
    marketForbes: "Балкон Форбс",
    marketSubtabLabel: "Подвкладки рынка",
    marketCapitalization: "Капитализация рынка",
    totalOdm: "Всего ODM",
    totalLdm: "Всего LDM",
    marketMembers: "Участники",
    changeSinceYesterday: "к предыдущему дню",
    previousDay: "Предыдущий день",
    noPreviousData: "Нет данных за предыдущий день.",
    capitalizationLoading: "Загружаем капитализацию рынка...",
    capitalizationEmpty: "Недостаточно данных для графика.",
    capitalizationError: "Не удалось загрузить капитализацию рынка.",
    marketLiveToday: "Текущий живой срез за сегодня",
    lastDays: "Последние дни",
    listings: "Лоты",
    marketRefresh: "Обновить",
    sellToBot: "Продать боту",
    listOnMarket: "Выставить на рынке",
    useService: "Использовать",
    selectStreamer: "Выберите стримера",
    marketBuyListing: "Купить лот",
    updateListingPrice: "Изменить цену",
    cancelListing: "Снять с продажи",
    listingOfferPriceLabel: "Цена (ODM)",
    listingOfferPricePlaceholder: "Цена в ODM",
    confirmSellToBotTitle: "Продажа боту",
    confirmSellToBotMessage:
      "Продать этот предмет боту? Итоговую сумму и условия подтверждает сервер при продаже.",
    confirmMarketPurchaseTitle: "Покупка на рынке",
    confirmMarketPurchaseMessage:
      "Купить этот лот? Списание ODM и передача предмета подтверждаются сервером.",
    confirmCancelListingTitle: "Снять лот",
    confirmCancelListingMessage: "Убрать ваш лот с рынка? Предмет вернётся в инвентарь — проверку делает сервер.",
    invalidPositiveFinitePrice: "Введите положительное конечное число (цена).",
    sellingToBot: "Продаём боту...",
    listingOnMarket: "Создаём лот...",
    usingService: "Используем сервис...",
    usingServiceLoadingTargets: "Загружаем стримеров...",
    marketBuyingListing: "Покупка...",
    updatingMarketPrice: "Обновляем цену...",
    cancellingMarketListing: "Отменяем лот...",
    inventoryAlreadyListedOnMarket: "Уже выставлено на рынке",
    noAvailableStreamers: "Нет доступных стримеров.",
    marketSellBotSuccessReceived: "Продано. Получено: {received} ODM.",
    marketSellBotSuccess: "Предмет продан боту.",
    marketListSuccess: "Лот создан.",
    marketListToast: "Лот создан: {itemName} за {price} ODM",
    inventoryServiceUseSuccess: "Сервис использован.",
    inventoryServiceUseSuccessConsumed: "Сервис использован, предмет списан.",
    inventoryServiceUseFailed: "Не удалось использовать сервис.",
    marketBuySuccess: "Покупка выполнена.",
    marketUpdatePriceSuccess: "Цена обновлена.",
    marketCancelSuccess: "Лот отменён.",
    marketMutationFailed: "Операция не выполнена.",
    toastCloseLabel: "Закрыть уведомление",
    expandItemActions: "Действия",
    collapseItemActions: "Скрыть действия",
    marketForbesDescription: "Топ 10 пользователей по ODM",
    marketForbesLoading: "Загружаем рейтинг Balkon Forbes...",
    marketForbesEmpty: "Пока нет данных для рейтинга.",
    marketForbesError: "Не удалось загрузить Balkon Forbes.",
    marketForbesRefresh: "Обновить",
    rank: "Место",
    fromGuild: "Родом из",
    hidden: "скрыто",
    streamerModeHidden: "Скрыто режимом стримера",
    noHomeGuild: "Гильдия не выбрана",
    noDescription: "Описание отсутствует.",
    topByOdm: "Топ 10 пользователей по ODM",
    botShopLoading: "Загружаем магазин бота...",
    botShopEmpty: "Магазин бота пока пуст.",
    botShopError: "Не удалось загрузить магазин бота.",
    botShopPrice: "Цена",
    botShopRefresh: "Обновить",
    shopOverview: "Обзор",
    shopItems: "Предметы",
    shopCases: "Кейсы",
    shopObs: "OBS",
    shopCasesSoon: "Кейсы скоро появятся.",
    shopObsStreamers: "Стримеры OBS",
    shopObsEmpty: "Стримеры не зарегистрированы.",
    shopObsLoading: "Загружаем стримеров...",
    shopObsError: "Не удалось загрузить стримеров OBS.",
    twitch: "Twitch",
    openStreamer: "Открыть",
    backToStreamers: "Назад к стримерам",
    streamerPrimary: "Основной",
    agentConnected: "Агент подключен",
    agentOffline: "Агент оффлайн",
    agentOfflineRecently: "Агент оффлайн · был недавно",
    agentNotConfigured: "Агент не настроен",
    streamLive: "В эфире",
    streamOffline: "Оффлайн",
    streamUnknown: "Не отслеживается",
    media: "Медиа",
    showImageFiveSeconds: "Показать изображение на 5 секунд",
    showGifFiveSeconds: "Показать GIF на 5 секунд",
    durationSeconds: "Длительность, сек",
    purchaseSoon: "Скоро",
    obsMediaPurchaseSuccess: "Эффект отправлен.",
    obsMediaPurchaseFailed: "Не удалось отправить OBS эффект.",
    effectSent: "Эффект отправлен",
    purchaseUnavailable: "Недоступно",
    obsMediaDescription: "Покупка медиа-эффектов для стримерских сцен OBS.",
    obsMediaHistory: "История",
    obsMediaHistoryEmpty: "Покупок OBS медиа пока нет.",
    obsMediaHistoryError: "Не удалось загрузить историю OBS медиа.",
    obsMediaHistoryLoading: "Загружаем историю OBS медиа...",
    obsActionStatusPending: "Ожидает",
    obsActionStatusSent: "Отправлено",
    obsActionStatusFailed: "Ошибка",
    obsActionStatusRefunded: "Возвращено",
    refunded: "Возврат",
    commandId: "ID команды",
    errorMessage: "Ошибка",
    craftLoading: "Загружаем рецепты крафта...",
    craftEmpty: "Рецептов крафта пока нет.",
    craftError: "Не удалось загрузить рецепты крафта.",
    craftRefresh: "Обновить",
    craftResult: "Результат",
    craftIngredients: "Ингредиенты",
    craftRecipeId: "Рецепт",
    craftResultItemId: "ID результата",
    profileSection: "Профиль пользователя",
    profileSettings: "Настройки публичного профиля",
    streamerMode: "Режим стримера",
    homeGuild: "Домашний сервер",
    selectHomeGuild: "Выберите домашний сервер",
    guildNotSelected: "Сервер не выбран",
    discordProfileNotCached: "Discord профиль не закеширован",
    publicDescription: "Публичное описание",
    publicDescriptionPlaceholder: "Расскажите о себе или оставьте рекламу...",
    publicDescriptionPublicWarning: "Описание публичное. Позже здесь появится модерация.",
    saveProfile: "Сохранить профиль",
    profileSaved: "Профиль сохранен.",
    profileSaveFailed: "Не удалось сохранить профиль.",
    apiReachFailedHint: "Не удалось связаться с API. Проверьте, что API запущен и CORS разрешает PATCH.",
    charactersLeft: "Осталось символов",
    notSelected: "Не выбрано",
    tradeableYes: "Можно передать",
    tradeableNo: "Нельзя передать",
    sellableYes: "Можно продать",
    sellableNo: "Нельзя продать",
    botSell: "Продажа боту",
    unknownDate: "Неизвестно",
    checking: "Проверяем данные...",
    previous: "Назад",
    next: "Далее",
    page: "Страница",
    status: "Status",
    statusOnline: "Работает",
    statusOffline: "Не работает",
    statusDevelopment: "На разработке",
    inventoryFilterAll: "Все",
    inventoryFilterMaterials: "Материалы",
    inventoryFilterSellable: "Продаваемые",
    inventoryFilterTradeable: "Передаваемые",
    inventoryFilterLabel: "Фильтр инвентаря",
    inventorySearchPlaceholder: "Поиск предметов...",
    inventorySearchNoResults: "Ничего не найдено.",
    inventorySearchClearAria: "Очистить поиск",
    itemsWord: "предметов",
    noSellableItems: "Нет продаваемых предметов.",
    noTradeableItems: "Нет передаваемых предметов.",
    noMaterialsItems: "Нет материалов.",
    notifications: "Уведомления",
    notificationEmpty: "Уведомлений пока нет.",
    notificationLoading: "Загружаем уведомления...",
    notificationError: "Не удалось загрузить уведомления.",
    notificationUnread: "Непрочитанные",
    obsNotificationTitle: "OBS эффект отправлен",
    obsNotificationBody: "Эффект отправлен стримеру.",
    obsNotificationEffectPrefix: "Эффект",
    obsNotificationSentTo: "отправлен стримеру",
    balanceUpdated: "Баланс обновлён",
    markRead: "Прочитать",
    markAllRead: "Прочитать все",
    viewAll: "Открыть все",
    unreadOnly: "Только непрочитанные",
    allNotifications: "Все уведомления",
    notificationRead: "Прочитано",
    notificationOpenLink: "Открыть ссылку",
    notificationRefresh: "Обновить",
    notificationBellAria: "Открыть уведомления",
    noNotificationsYet: "Пока уведомлений нет.",
    adminMode: "Режим",
    adminModeUser: "Пользователь",
    adminModeAdmin: "Админ",
    adminTabDashboard: "Dashboard",
    adminTabServers: "Серверы",
    adminTabLogs: "Логи",
    adminTabObs: "OBS",
    adminTabItems: "Предметы",
    adminEconomy: "Валюта",
    adminTabMessage: "Рассылка",
    adminStatsLoading: "Загружаем админ-статистику...",
    adminStatsError: "Не удалось загрузить админ-статистику.",
    adminStatsEmpty: "Нет данных админ-статистики.",
    retry: "Повторить",
    adminCountGuilds: "Гильдии",
    adminCountMembers: "Участники",
    adminCountItems: "Предметы",
    adminCountInventory: "Инвентарь",
    adminCountMarket: "Рынок",
    adminCountStore: "Магазин",
    adminCountRecipes: "Рецепты",
    adminCountStreamers: "Стримеры",
    adminCountSettings: "Настройки",
    adminCountActions: "Действия",
    adminLogsEmpty: "Логи bootstrap пока отсутствуют.",
    statusOk: "OK",
    statusError: "Ошибка",
    source: "Источник",
    updated: "Обновлено",
    channelsSynced: "Каналы синхр.",
    rolesSynced: "Роли синхр.",
    messageLabel: "Сообщение",
    adminObsEmpty: "Настройки OBS пока отсутствуют.",
    adminObsMediaActions: "OBS Media Actions",
    actionBuyer: "Покупатель",
    actionStreamer: "Стример",
    actionProduct: "Продукт",
    actionStatus: "Статус",
    allStatuses: "Все статусы",
    contributors: "Contributors",
    none: "Нет",
    adminServersSoon: "Секция серверов в разработке. Здесь будет управление гильдиями, доступами и bootstrap-проверками.",
    adminItemsSoon: "Секция предметов в разработке. Здесь будет модерация каталога и контроль экономики.",
    adminItemsTitle: "Управление каталогом",
    adminItemsRefresh: "Обновить",
    adminItemsLoading: "Загружаем предметы...",
    adminItemsEmpty: "Предметы не найдены.",
    adminItemsLoadError: "Не удалось загрузить каталог предметов.",
    adminItemsSaveError: "Не удалось сохранить предмет.",
    adminItemsDeleteError: "Не удалось удалить предмет.",
    adminItemsCreated: "Предмет создан.",
    adminItemsUpdated: "Предмет обновлен.",
    adminItemsDeleted: "Предмет удален.",
    adminItemsName: "Название",
    adminItemsDescription: "Описание",
    adminItemsType: "Тип",
    adminItemsRarity: "Редкость",
    adminItemsEmoji: "Эмодзи",
    adminItemsImageUrl: "URL изображения",
    adminItemsBotSellPrice: "Цена продажи боту",
    adminItemsTradeable: "Можно передавать",
    adminItemsSearchType: "Поиск типа",
    adminItemsSearchRarity: "Поиск редкости",
    adminItemsNoOptions: "Совпадений нет",
    adminItemsCreate: "Создать",
    adminItemsUpdate: "Сохранить",
    adminItemsCancelEdit: "Отмена",
    adminItemsEdit: "Редактировать",
    adminItemsDelete: "Удалить",
    adminItemsSearchPlaceholder: "Поиск по названию, типу или редкости...",
    adminItemsValidationRequired: "Заполните обязательные поля: название, описание, тип и редкость.",
    adminItemsValidationPrice: "Цена продажи боту должна быть числом не меньше 0.",
    adminItemsDeleteConfirmTitle: "Удалить предмет",
    adminItemsDeleteConfirmText: "Вы действительно хотите удалить:",
    adminItemsDeleteConfirmAction: "Подтвердить удаление",
    adminTabBotShop: "Магазин",
    adminBroadcast: "Рассылка",
    adminBroadcastTitle: "Заголовок",
    adminBroadcastBody: "Текст",
    adminBroadcastImageUrl: "URL изображения",
    adminBroadcastLinkUrl: "URL ссылки",
    adminBroadcastSeverity: "Важность",
    adminBroadcastPreview: "Предпросмотр",
    adminBroadcastSend: "Отправить",
    adminBroadcastSending: "Отправляем...",
    adminBroadcastSent: "Уведомление отправлено. Получателей:",
    adminBroadcastFailed: "Не удалось отправить уведомление.",
    severityInfo: "Инфо",
    severitySuccess: "Успех",
    severityWarning: "Внимание",
    severityDanger: "Важно",
    adminBotShopTitle: "Управление магазином",
    adminBotShopRefresh: "Обновить",
    adminBotShopLoading: "Загружаем магазин...",
    adminBotShopEmpty: "Магазин пуст.",
    adminBotShopLoadError: "Не удалось загрузить магазин.",
    adminBotShopSaveError: "Не удалось сохранить позицию.",
    adminBotShopDeleteError: "Не удалось удалить позицию.",
    adminBotShopSaved: "Позиция сохранена.",
    adminBotShopDeleted: "Позиция удалена.",
    adminBotShopAddTitle: "Добавить / обновить позицию",
    adminBotShopSelectItem: "Выберите предмет",
    adminBotShopSearchItem: "Поиск предмета...",
    adminBotShopNoResults: "Совпадений нет",
    adminBotShopPrice: "Цена",
    adminBotShopSave: "Сохранить",
    adminBotShopSelectedItem: "Выбранный предмет",
    adminBotShopClearItem: "Очистить",
    adminBotShopValidationItem: "Выберите предмет из списка.",
    adminBotShopValidationInvalidId: "Выбранный предмет имеет неверный идентификатор.",
    adminBotShopValidationPrice: "Цена должна быть числом больше 0.",
    adminBotShopDeleteConfirmTitle: "Удалить позицию",
    adminBotShopDeleteConfirmText: "Вы действительно хотите удалить позицию для:",
    adminBotShopDeleteConfirmAction: "Подтвердить удаление",
    adminBotShopCancel: "Отмена",
    adminBotShopDelete: "Удалить",
    adminBotShopListingId: "Лот",
    adminEconomyTitle: "Корректировка баланса",
    adminEconomyDescription: "Выдача или списание ODM/LDM для тестов, наград и компенсаций.",
    targetDiscordId: "Discord ID пользователя",
    currency: "Валюта",
    adminEconomyReason: "Причина",
    adjustBalance: "Изменить баланс",
    adjustingBalance: "Изменяем баланс...",
    balanceAdjusted: "Баланс обновлен.",
    balanceAdjustFailed: "Не удалось изменить баланс.",
    balanceAfter: "Баланс после",
    economyAuditNotice: "Операция записывается в журнал.",
    positiveAmountHint: "Положительное число добавляет баланс.",
    negativeAmountHint: "Отрицательное число списывает баланс.",
    quickPresets: "Быстрые суммы",
  },
  en: {
    welcome: "Welcome to Balkon",
    title: "Balkon",
    subtitle: "Discord bot dashboard for economy, streamers and OBS control.",
    loginWithDiscord: "Login with Discord",
    searching: "Search tabs...",
    marketOverviewSearchDescription: "Capitalization and ODM chart",
    marketListingsSearchDescription: "Player items listed for sale",
    marketForbesSearchDescription: "Top 10 users by ODM",
    botShopSearchDescription: "Buy items from bot shop",
    inventorySearchDescription: "Your items, selling and transfers",
    craftSearchDescription: "Recipes and item crafting",
    profileSearchDescription: "Account and Discord profile",
    loadingSession: "Checking session...",
    loadingInventory: "Loading inventory...",
    inventoryEmpty: "Inventory is empty.",
    noRoles: "No roles assigned",
    discordId: "Discord ID",
    obtained: "Obtained",
    itemDetails: "Item details",
    close: "Close",
    itemId: "Item ID",
    templateId: "Template ID",
    owner: "Owner",
    originalOwner: "Original owner",
    rarity: "Rarity",
    type: "Type",
    tier: "Tier",
    botSellPrice: "Bot sell price",
    noItemSelected: "No item selected.",
    selectItemHint: "Select an item on the left to view full details.",
    tabOverview: "Overview",
    tabInventory: "Inventory",
    tabMarket: "Market",
    tabBotShop: "Bot Shop",
    tabCraft: "Craft",
    tabProfile: "Profile",
    tabNotifications: "Notifications",
    tabServers: "Servers",
    tabStreamerStudio: "Streamer Studio",
    navMain: "Main",
    navPersonal: "Personal",
    navEconomy: "Economy",
    navObs: "Streams",
    navServers: "Servers",
    navAdmin: "Admin",
    myServers: "My Servers",
    serversComingSoon: "Soon",
    serverManagementDescription: "Soon you will be able to select a Discord server and manage economy, members, and settings.",
    serversTitle: "My servers",
    serversSubtitle: "Choose a registered Discord server to review its status and prepare management tools.",
    serversEmpty: "No registered servers yet.",
    serversError: "Failed to load servers.",
    serversRefresh: "Refresh",
    openServer: "Open",
    backToServers: "Back to servers",
    serverRoleOwner: "Owner",
    serverRoleAdmin: "Admin",
    serverRoleMember: "Member",
    serverRoleUnknown: "Unknown",
    serverHomeGuild: "Home guild",
    serverMembers: "Members",
    serverStreamers: "Streamers",
    serverItems: "Items",
    serverInventory: "Inventory",
    serverMarketListings: "Market listings",
    serverTabOverview: "Overview",
    serverTabEconomy: "Economy",
    serverTabMembers: "Members",
    serverTabLogs: "Logs",
    serverTabSettings: "Settings",
    serverSectionComingSoon: "Management for this section will appear here soon.",
    obsShop: "OBS Shop",
    obsHistory: "OBS History",
    streamerStudioTitle: "Streamer Studio",
    streamerStudioSubtitle: "Control OBS scenes and element placement from the browser.",
    streamerStudioRefresh: "Refresh",
    streamerStudioEmpty: "No accessible streamers.",
    streamerStudioError: "Failed to load Streamer Studio.",
    streamerStudioOpenControl: "Open control",
    streamerStudioBack: "Back",
    streamerStudioRoleOwner: "Owner",
    streamerStudioRoleManager: "Manager",
    streamerStudioRoleModerator: "Moderator",
    streamerStudioRoleBotAdmin: "Bot admin",
    streamerStudioCanControl: "Can control",
    streamerStudioCanManage: "Can manage",
    streamerStudioAgentOnline: "OBS agent online",
    streamerStudioAgentOffline: "OBS agent offline",
    streamerStudioAgentNotConfigured: "OBS agent not configured",
    streamerStudioAgentVersionLabel: "Agent version",
    streamerStudioRelayProtocolLabel: "Relay protocol",
    streamerStudioCapabilitiesLabel: "Capabilities",
    streamerStudioObsStatusLabel: "OBS",
    streamerStudioObsConnected: "connected",
    streamerStudioObsDisconnected: "not connected",
    streamerStudioObsVersionLabel: "OBS version",
    streamerStudioObsWebsocketVersionLabel: "obs-websocket version",
    streamerStudioCapabilitiesUnknown: "OBS Agent capabilities are unknown. Update and restart the agent if advanced controls fail.",
    streamerStudioCapabilityUnsupported: "OBS Agent is outdated or does not support this command. Update and restart the agent.",
    streamerStudioObsNotConnected: "OBS is not connected. Open OBS and reconnect the agent.",
    streamerStudioScenes: "Scenes",
    streamerStudioLoadScenes: "Load scenes",
    streamerStudioRefreshScenes: "Refresh scenes",
    streamerStudioRefreshItems: "Refresh items",
    streamerStudioLoadingScenes: "Loading scenes...",
    streamerStudioLoadingItems: "Loading scene items...",
    streamerStudioSceneItems: "Scene items",
    streamerStudioNoScenes: "No scenes",
    streamerStudioNoItems: "No items",
    streamerStudioSelectScene: "Select scene",
    streamerStudioPreview: "Preview",
    streamerStudioInspector: "Inspector",
    streamerStudioUnknownInput: "unknown",
    streamerStudioTypeGroup: "group",
    streamerStudioRecommended: "Recommended",
    streamerStudioEnabled: "Enabled",
    streamerStudioDisabled: "Disabled",
    streamerStudioApplyTransform: "Apply to OBS",
    streamerStudioResetTransform: "Reset changes",
    streamerStudioUnsavedChanges: "There are unsaved changes",
    streamerStudioTransformApplied: "Transform applied",
    streamerStudioTransformApplyFailed: "Failed to apply transform",
    streamerStudioLayerControlsTitle: "Layer",
    streamerStudioMoveLayerUp: "Move up",
    streamerStudioMoveLayerDown: "Move down",
    streamerStudioMoveLayerTop: "To top",
    streamerStudioMoveLayerBottom: "To bottom",
    streamerStudioLayerApplied: "Layer order updated",
    streamerStudioLayerApplyFailed: "Failed to update layer order",
    streamerStudioVisibilityControlsTitle: "Visibility",
    streamerStudioShowItem: "Show",
    streamerStudioHideItem: "Hide",
    streamerStudioRemoveItem: "Remove",
    streamerStudioVisibilityApplied: "Visibility updated",
    streamerStudioVisibilityApplyFailed: "Failed to update visibility",
    streamerStudioRemoveApplied: "Item removed from scene",
    streamerStudioRemoveFailed: "Failed to remove item",
    streamerStudioRemoveConfirm: "Remove this item from the current OBS scene?",
    streamerStudioRemoveHint: "Removes the item only from the current scene.",
    streamerStudioTransformX: "X",
    streamerStudioTransformY: "Y",
    streamerStudioTransformScaleX: "Scale X",
    streamerStudioTransformScaleY: "Scale Y",
    streamerStudioTransformRotation: "Rotation",
    streamerStudioDragHint: "Drag selected item or edit values manually",
    streamerStudioLayerOrderHint: "Same order as OBS: upper items render above lower items.",
    streamerStudioDirtyRefreshConfirm: "You have unsaved changes. Refresh items and discard them?",
    streamerStudioForbiddenHint: "You do not have access to control this streamer.",
    streamerStudioCreateSourceTitle: "Create source",
    streamerStudioCreateTextTitle: "Text",
    streamerStudioCreateTextSubtitle: "Add a text source to the selected OBS scene.",
    streamerStudioCreateTextContent: "Text",
    streamerStudioCreateTextSourceName: "Source name",
    streamerStudioCreateTextSourceNamePlaceholder: "For example: Balkon Text",
    streamerStudioCreateTextButton: "Add text",
    streamerStudioCreateTextSuccess: "Text source created",
    streamerStudioCreateTextFailed: "Failed to create text source",
    streamerStudioCreateTextInvalid: "Enter text up to 500 characters.",
    streamerStudioCreateTextOpen: "Open",
    streamerStudioCreateTextCollapse: "Collapse",
    streamerStudioSourceSettingsTitle: "Source settings",
    streamerStudioSourceSettingsLoading: "Loading source settings...",
    streamerStudioSourceSettingsLoadFailed: "Failed to load source settings",
    streamerStudioTextSettingsTitle: "Text",
    streamerStudioTextSettingsContent: "Content",
    streamerStudioTextSettingsPlaceholder: "Enter new source text",
    streamerStudioTextSettingsUpdate: "Update text",
    streamerStudioTextSettingsSuccess: "Text source updated",
    streamerStudioTextSettingsFailed: "Failed to update text source",
    streamerStudioTextSettingsInvalid: "Enter between 1 and 500 characters.",
    streamerStudioCreateBrowserTitle: "Browser URL",
    streamerStudioCreateBrowserSubtitle: "Add a browser source by URL to the selected OBS scene.",
    streamerStudioCreateBrowserUrl: "URL",
    streamerStudioCreateBrowserUrlPlaceholder: "https://example.com/widget",
    streamerStudioCreateBrowserWidth: "Width",
    streamerStudioCreateBrowserHeight: "Height",
    streamerStudioCreateBrowserButton: "Add Browser",
    streamerStudioCreateBrowserSuccess: "Browser source created",
    streamerStudioCreateBrowserFailed: "Failed to create browser source",
    streamerStudioCreateBrowserInvalid: "Enter a valid http/https URL.",
    streamerStudioBrowserSettingsTitle: "Browser source",
    streamerStudioBrowserSettingsUrl: "URL",
    streamerStudioBrowserSettingsUrlPlaceholder: "https://example.com/widget",
    streamerStudioBrowserSettingsWidth: "Width",
    streamerStudioBrowserSettingsHeight: "Height",
    streamerStudioBrowserSettingsUpdate: "Update Browser",
    streamerStudioBrowserSettingsSuccess: "Browser source updated",
    streamerStudioBrowserSettingsFailed: "Failed to update browser source",
    streamerStudioBrowserSettingsInvalid: "Provide at least one field and use a valid http/https URL.",
    streamerStudioCreateSourceTypeText: "Text",
    streamerStudioCreateSourceTypeBrowser: "Browser",
    streamerStudioTrustedUsersTitle: "Trusted users",
    streamerStudioTrustedUsersSubtitle: "Add people who can control your OBS scene for free.",
    streamerStudioTrustedUsersRefresh: "Refresh",
    streamerStudioTrustedUsersOpen: "Open",
    streamerStudioTrustedUsersCollapse: "Collapse",
    streamerStudioTrustedUsersCount: "{count} trusted",
    streamerStudioTrustedUsersEmpty: "No trusted users yet.",
    streamerStudioTrustedUsersDiscordId: "Discord ID",
    streamerStudioTrustedUsersRole: "Role",
    streamerStudioTrustedUsersAdd: "Add",
    streamerStudioTrustedUsersRemove: "Remove",
    streamerStudioTrustedUsersModerator: "Moderator",
    streamerStudioTrustedUsersManager: "Manager",
    streamerStudioTrustedUsersAddSuccess: "User added",
    streamerStudioTrustedUsersRemoveSuccess: "Access removed",
    streamerStudioTrustedUsersLoadFailed: "Failed to load trusted users",
    streamerStudioTrustedUsersSaveFailed: "Failed to save access",
    streamerStudioTrustedUsersDeleteFailed: "Failed to remove access",
    streamerStudioTrustedUsersInvalidDiscordId: "Discord ID must contain only digits and be no longer than 32 characters.",
    streamerStudioTrustedUsersManagerHint: "A manager can control the scene and manage trusted users.",
    streamerStudioAgentSetupTitle: "OBS Agent setup",
    streamerStudioAgentSetupSubtitle: "Connect the local Balkon OBS Agent for browser-based scene and source control.",
    streamerStudioAgentSetupRefresh: "Refresh status",
    streamerStudioAgentSetupConfigured: "Binding configured",
    streamerStudioAgentSetupNotConfigured: "Binding not configured",
    streamerStudioAgentSetupReady: "Agent is ready",
    streamerStudioAgentSetupOfflineHint: "OBS Agent is offline",
    streamerStudioAgentSetupObsDisconnectedHint: "OBS is not connected. Open OBS and reconnect the agent.",
    streamerStudioAgentSetupTokenPresent: "Token stored",
    streamerStudioAgentSetupTokenMissing: "Token missing",
    streamerStudioAgentSetupLastSeen: "Last seen",
    streamerStudioAgentSetupUnknown: "Unknown",
    streamerStudioAgentSetupTabStatus: "Status",
    streamerStudioAgentSetupTabSetup: "Setup",
    streamerStudioAgentSetupTabToken: "Token",
    streamerStudioAgentSetupTabManualBind: "Manual bind",
    streamerStudioAgentSetupTabDanger: "Danger",
    streamerStudioAgentSetupInstructionsTitle: "How to connect the agent",
    streamerStudioAgentSetupInstructionInstall: "1. Install or open Balkon OBS Agent on the streamer PC.",
    streamerStudioAgentSetupInstructionRelay: "2. Enter the Relay URL.",
    streamerStudioAgentSetupInstructionAgentId: "3. Enter the Agent ID.",
    streamerStudioAgentSetupInstructionAgentToken: "4. Enter the Agent Token.",
    streamerStudioAgentSetupInstructionObs: "5. Enter the OBS WebSocket URL and password in the agent.",
    streamerStudioAgentSetupInstructionStart: "6. Start the agent and wait for it to connect.",
    streamerStudioAgentSetupRelayUnavailable: "Relay URL is not published by the backend yet. Use your deployment relay URL from configuration.",
    streamerStudioAgentSetupRelayLabel: "Relay URL",
    streamerStudioAgentSetupAgentIdLabel: "Agent ID",
    streamerStudioAgentSetupTokenLabel: "Agent Token",
    streamerStudioAgentSetupCustomAgentId: "Custom Agent ID",
    streamerStudioAgentSetupCustomAgentIdPlaceholder: "Leave empty to auto-generate",
    streamerStudioAgentSetupGenerateToken: "Generate / rotate token",
    streamerStudioAgentSetupGenerating: "Generating token...",
    streamerStudioAgentSetupCopy: "Copy",
    streamerStudioAgentSetupCopied: "Copied",
    streamerStudioAgentSetupCopyFailed: "Copy failed",
    streamerStudioAgentSetupOneTimeTitle: "New token",
    streamerStudioAgentSetupOneTimeWarning: "Copy this token now. It will not be shown again.",
    streamerStudioAgentSetupCopyNowWarning: "Copy the token now. It will not be shown again after you leave this view.",
    streamerStudioAgentSetupBindTitle: "Manual bind",
    streamerStudioAgentSetupBindSubtitle: "Use this if you already have an Agent ID and Agent Token.",
    streamerStudioAgentSetupBindButton: "Save binding",
    streamerStudioAgentSetupBinding: "Saving...",
    streamerStudioAgentSetupBindSuccess: "Binding saved",
    streamerStudioAgentSetupBindFailed: "Failed to save binding",
    streamerStudioAgentSetupProvisionSuccess: "New token generated",
    streamerStudioAgentSetupProvisionFailed: "Failed to generate token",
    streamerStudioAgentSetupClear: "Clear binding",
    streamerStudioAgentSetupClearing: "Clearing...",
    streamerStudioAgentSetupClearSuccess: "Binding cleared",
    streamerStudioAgentSetupClearFailed: "Failed to clear binding",
    streamerStudioAgentSetupClearConfirm: "Remove the current OBS Agent binding for this streamer?",
    streamerStudioAgentSetupClearWarning: "This removes the current OBS Agent binding for the streamer. You will need to set it up or bind it again.",
    streamerStudioAgentSetupInvalidBind: "Provide both Agent ID and Agent Token.",
    configure: "Configure",
    quickActions: "Quick actions",
    recentActivity: "Recent activity",
    overviewNotLoaded: "Not loaded",
    overviewOpenInventory: "Open inventory",
    overviewProfileHint: "Set your home server and public description.",
    overviewRecentEmpty: "No recent activity yet.",
    overviewLoadFailed: "Failed to load overview.",
    overviewShowcaseEyebrow: "Showcase",
    overviewShowcaseTitle: "Balkon Showcase",
    overviewShowcaseSubtitle: "A 3D showcase for Balkon items, effects, and events will live here.",
    overviewModelSoon: "3D model coming soon",
    profile: "Profile",
    logout: "Logout",
    balance: "Balance",
    odm: "ODM",
    ldm: "LDM",
    balanceLoadFailed: "Failed to load balance.",
    buy: "Buy",
    buying: "Buying...",
    amount: "Amount",
    total: "Total",
    notEnoughBalance: "Not enough ODM.",
    purchaseSuccess: "Purchased!",
    purchaseFailed: "Purchase failed.",
    languages: "Language",
    marketSoon: "Market section is coming soon.",
    marketLoading: "Loading market...",
    marketEmpty: "No market listings yet.",
    marketError: "Failed to load market.",
    marketPrice: "Price",
    marketSeller: "Seller",
    marketListingId: "Listing",
    marketInventoryItemId: "Inventory ID",
    marketOverview: "Overview",
    marketListings: "Listings",
    marketForbes: "Balkon Forbes",
    marketSubtabLabel: "Market subtabs",
    marketCapitalization: "Market capitalization",
    totalOdm: "Total ODM",
    totalLdm: "Total LDM",
    marketMembers: "Members",
    changeSinceYesterday: "vs previous day",
    previousDay: "Previous day",
    noPreviousData: "No previous-day data.",
    capitalizationLoading: "Loading market capitalization...",
    capitalizationEmpty: "Not enough data for chart.",
    capitalizationError: "Failed to load market capitalization.",
    marketLiveToday: "Current live snapshot for today",
    lastDays: "Last days",
    listings: "Listings",
    marketRefresh: "Refresh",
    sellToBot: "Sell to bot",
    listOnMarket: "List on market",
    useService: "Use service",
    selectStreamer: "Select streamer",
    marketBuyListing: "Buy listing",
    updateListingPrice: "Update price",
    cancelListing: "Cancel listing",
    listingOfferPriceLabel: "Price (ODM)",
    listingOfferPricePlaceholder: "Price in ODM",
    confirmSellToBotTitle: "Sell to bot",
    confirmSellToBotMessage:
      "Sell this item to the bot? The server confirms the payout and eligibility when you sell.",
    confirmMarketPurchaseTitle: "Buy market listing",
    confirmMarketPurchaseMessage:
      "Buy this listing? ODM debit and transfer are enforced by the server.",
    confirmCancelListingTitle: "Cancel listing",
    confirmCancelListingMessage: "Remove your listing from the market? Item return rules are enforced by the server.",
    invalidPositiveFinitePrice: "Enter a positive finite price.",
    sellingToBot: "Selling…",
    listingOnMarket: "Creating listing…",
    usingService: "Using service…",
    usingServiceLoadingTargets: "Loading streamers...",
    marketBuyingListing: "Buying…",
    updatingMarketPrice: "Updating price…",
    cancellingMarketListing: "Cancelling…",
    inventoryAlreadyListedOnMarket: "Already listed on market",
    noAvailableStreamers: "No available streamers.",
    marketSellBotSuccessReceived: "Sold. Received {received} ODM.",
    marketSellBotSuccess: "Item sold to the bot.",
    marketListSuccess: "Listing created.",
    marketListToast: "Listing created: {itemName} for {price} ODM",
    inventoryServiceUseSuccess: "Service used.",
    inventoryServiceUseSuccessConsumed: "Service used, item consumed.",
    inventoryServiceUseFailed: "Failed to use service.",
    marketBuySuccess: "Purchase complete.",
    marketUpdatePriceSuccess: "Price updated.",
    marketCancelSuccess: "Listing cancelled.",
    marketMutationFailed: "Action failed.",
    toastCloseLabel: "Close notification",
    expandItemActions: "Actions",
    collapseItemActions: "Hide actions",
    marketForbesDescription: "Top 10 users by ODM",
    marketForbesLoading: "Loading Balkon Forbes leaderboard...",
    marketForbesEmpty: "No leaderboard data yet.",
    marketForbesError: "Failed to load Balkon Forbes.",
    marketForbesRefresh: "Refresh",
    rank: "Rank",
    fromGuild: "From",
    hidden: "hidden",
    streamerModeHidden: "Hidden by streamer mode",
    noHomeGuild: "No home guild selected",
    noDescription: "No public description.",
    topByOdm: "Top 10 users by ODM",
    botShopLoading: "Loading bot shop...",
    botShopEmpty: "Bot shop is empty for now.",
    botShopError: "Failed to load bot shop.",
    botShopPrice: "Price",
    botShopRefresh: "Refresh",
    shopOverview: "Overview",
    shopItems: "Items",
    shopCases: "Cases",
    shopObs: "OBS",
    shopCasesSoon: "Cases are coming soon.",
    shopObsStreamers: "OBS Streamers",
    shopObsEmpty: "No streamers registered yet.",
    shopObsLoading: "Loading streamers...",
    shopObsError: "Failed to load OBS streamers.",
    twitch: "Twitch",
    openStreamer: "Open",
    backToStreamers: "Back to streamers",
    streamerPrimary: "Primary",
    agentConnected: "Agent connected",
    agentOffline: "Agent offline",
    agentOfflineRecently: "Agent offline · seen recently",
    agentNotConfigured: "Agent not configured",
    streamLive: "Live",
    streamOffline: "Offline",
    streamUnknown: "Unknown",
    media: "Media",
    showImageFiveSeconds: "Show image for 5 seconds",
    showGifFiveSeconds: "Show GIF for 5 seconds",
    durationSeconds: "Duration, sec",
    purchaseSoon: "Soon",
    obsMediaPurchaseSuccess: "Effect sent.",
    obsMediaPurchaseFailed: "Failed to send OBS effect.",
    effectSent: "Effect sent",
    purchaseUnavailable: "Unavailable",
    obsMediaDescription: "Purchase media effects for streamer OBS scenes.",
    obsMediaHistory: "History",
    obsMediaHistoryEmpty: "No OBS media purchases yet.",
    obsMediaHistoryError: "Failed to load OBS media history.",
    obsMediaHistoryLoading: "Loading OBS media history...",
    obsActionStatusPending: "Pending",
    obsActionStatusSent: "Sent",
    obsActionStatusFailed: "Failed",
    obsActionStatusRefunded: "Refunded",
    refunded: "Refunded",
    commandId: "Command ID",
    errorMessage: "Error",
    craftLoading: "Loading craft recipes...",
    craftEmpty: "No craft recipes yet.",
    craftError: "Failed to load craft recipes.",
    craftRefresh: "Refresh",
    craftResult: "Result",
    craftIngredients: "Ingredients",
    craftRecipeId: "Recipe",
    craftResultItemId: "Result ID",
    profileSection: "User profile",
    profileSettings: "Public profile settings",
    streamerMode: "Streamer mode",
    homeGuild: "Home server",
    selectHomeGuild: "Select home server",
    guildNotSelected: "Server not selected",
    discordProfileNotCached: "Discord profile not cached",
    publicDescription: "Public description",
    publicDescriptionPlaceholder: "Tell others about yourself or leave a promo...",
    publicDescriptionPublicWarning: "Description is public. Moderation will be added later.",
    saveProfile: "Save profile",
    profileSaved: "Profile saved.",
    profileSaveFailed: "Failed to save profile.",
    apiReachFailedHint: "Could not reach API. Check if API server is running and CORS allows PATCH.",
    charactersLeft: "Characters left",
    notSelected: "Not selected",
    tradeableYes: "Tradeable",
    tradeableNo: "Not tradeable",
    sellableYes: "Sellable",
    sellableNo: "Not sellable",
    botSell: "Bot sell",
    unknownDate: "Unknown",
    checking: "Checking data...",
    previous: "Previous",
    next: "Next",
    page: "Page",
    status: "Status",
    statusOnline: "Online",
    statusOffline: "Offline",
    statusDevelopment: "In development",
    inventoryFilterAll: "All",
    inventoryFilterMaterials: "Materials",
    inventoryFilterSellable: "Sellable",
    inventoryFilterTradeable: "Tradeable",
    inventoryFilterLabel: "Inventory filter",
    inventorySearchPlaceholder: "Search items...",
    inventorySearchNoResults: "No items found.",
    inventorySearchClearAria: "Clear search",
    itemsWord: "items",
    noSellableItems: "No sellable items yet.",
    noTradeableItems: "No tradeable items yet.",
    noMaterialsItems: "No materials yet.",
    notifications: "Notifications",
    notificationEmpty: "No notifications yet.",
    notificationLoading: "Loading notifications...",
    notificationError: "Failed to load notifications.",
    notificationUnread: "Unread",
    obsNotificationTitle: "OBS effect sent",
    obsNotificationBody: "Effect sent to streamer.",
    obsNotificationEffectPrefix: "Effect",
    obsNotificationSentTo: "sent to",
    balanceUpdated: "Balance updated",
    markRead: "Mark read",
    markAllRead: "Mark all read",
    viewAll: "View all",
    unreadOnly: "Unread only",
    allNotifications: "All notifications",
    notificationRead: "Read",
    notificationOpenLink: "Open link",
    notificationRefresh: "Refresh",
    notificationBellAria: "Open notifications",
    noNotificationsYet: "No notifications yet.",
    adminMode: "Mode",
    adminModeUser: "User",
    adminModeAdmin: "Admin",
    adminTabDashboard: "Dashboard",
    adminTabServers: "Servers",
    adminTabLogs: "Logs",
    adminTabObs: "OBS",
    adminTabItems: "Items",
    adminEconomy: "Currency",
    adminTabMessage: "Broadcast",
    adminStatsLoading: "Loading admin stats...",
    adminStatsError: "Failed to load admin stats.",
    adminStatsEmpty: "No admin stats available.",
    retry: "Retry",
    adminCountGuilds: "Guilds",
    adminCountMembers: "Members",
    adminCountItems: "Items",
    adminCountInventory: "Inventory",
    adminCountMarket: "Market",
    adminCountStore: "Store",
    adminCountRecipes: "Recipes",
    adminCountStreamers: "Streamers",
    adminCountSettings: "Settings",
    adminCountActions: "Actions",
    adminLogsEmpty: "No bootstrap logs yet.",
    statusOk: "OK",
    statusError: "Error",
    source: "Source",
    updated: "Updated",
    channelsSynced: "Channels synced",
    rolesSynced: "Roles synced",
    messageLabel: "Message",
    adminObsEmpty: "No OBS settings available.",
    adminObsMediaActions: "OBS Media Actions",
    actionBuyer: "Buyer",
    actionStreamer: "Streamer",
    actionProduct: "Product",
    actionStatus: "Status",
    allStatuses: "All statuses",
    contributors: "Contributors",
    none: "None",
    adminServersSoon: "Servers section is in progress. Guild management, access controls and bootstrap checks will appear here.",
    adminItemsSoon: "Items section is in progress. Catalog moderation and economy control tools will appear here.",
    adminItemsTitle: "Catalog Management",
    adminItemsRefresh: "Refresh",
    adminItemsLoading: "Loading items...",
    adminItemsEmpty: "No items found.",
    adminItemsLoadError: "Failed to load item catalog.",
    adminItemsSaveError: "Failed to save item.",
    adminItemsDeleteError: "Failed to delete item.",
    adminItemsCreated: "Item created.",
    adminItemsUpdated: "Item updated.",
    adminItemsDeleted: "Item deleted.",
    adminItemsName: "Name",
    adminItemsDescription: "Description",
    adminItemsType: "Type",
    adminItemsRarity: "Rarity",
    adminItemsEmoji: "Emoji",
    adminItemsImageUrl: "Image URL",
    adminItemsBotSellPrice: "Bot sell price",
    adminItemsTradeable: "Tradeable",
    adminItemsSearchType: "Search type",
    adminItemsSearchRarity: "Search rarity",
    adminItemsNoOptions: "No matches",
    adminItemsCreate: "Create",
    adminItemsUpdate: "Save",
    adminItemsCancelEdit: "Cancel",
    adminItemsEdit: "Edit",
    adminItemsDelete: "Delete",
    adminItemsSearchPlaceholder: "Search by name, type or rarity...",
    adminItemsValidationRequired: "Fill all required fields: name, description, type and rarity.",
    adminItemsValidationPrice: "Bot sell price must be a number greater or equal to 0.",
    adminItemsDeleteConfirmTitle: "Delete item",
    adminItemsDeleteConfirmText: "Do you really want to delete:",
    adminItemsDeleteConfirmAction: "Confirm delete",
    adminTabBotShop: "Bot Shop",
    adminBroadcast: "Broadcast",
    adminBroadcastTitle: "Title",
    adminBroadcastBody: "Message",
    adminBroadcastImageUrl: "Image URL",
    adminBroadcastLinkUrl: "Link URL",
    adminBroadcastSeverity: "Severity",
    adminBroadcastPreview: "Preview",
    adminBroadcastSend: "Send",
    adminBroadcastSending: "Sending...",
    adminBroadcastSent: "Notification sent. Recipients:",
    adminBroadcastFailed: "Failed to send notification.",
    severityInfo: "Info",
    severitySuccess: "Success",
    severityWarning: "Warning",
    severityDanger: "Danger",
    adminBotShopTitle: "Bot Shop Management",
    adminBotShopRefresh: "Refresh",
    adminBotShopLoading: "Loading bot shop...",
    adminBotShopEmpty: "Bot shop is empty.",
    adminBotShopLoadError: "Failed to load bot shop.",
    adminBotShopSaveError: "Failed to save listing.",
    adminBotShopDeleteError: "Failed to delete listing.",
    adminBotShopSaved: "Listing saved.",
    adminBotShopDeleted: "Listing deleted.",
    adminBotShopAddTitle: "Add / update listing",
    adminBotShopSelectItem: "Select item",
    adminBotShopSearchItem: "Search item...",
    adminBotShopNoResults: "No matches",
    adminBotShopPrice: "Price",
    adminBotShopSave: "Save",
    adminBotShopSelectedItem: "Selected item",
    adminBotShopClearItem: "Clear",
    adminBotShopValidationItem: "Please select an item from the list.",
    adminBotShopValidationInvalidId: "Selected item has invalid id.",
    adminBotShopValidationPrice: "Price must be a number greater than 0.",
    adminBotShopDeleteConfirmTitle: "Delete listing",
    adminBotShopDeleteConfirmText: "Do you really want to delete listing for:",
    adminBotShopDeleteConfirmAction: "Confirm delete",
    adminBotShopCancel: "Cancel",
    adminBotShopDelete: "Delete",
    adminBotShopListingId: "Listing",
    adminEconomyTitle: "Balance adjustment",
    adminEconomyDescription: "Grant or deduct ODM/LDM for testing, rewards, and compensation.",
    targetDiscordId: "User Discord ID",
    currency: "Currency",
    adminEconomyReason: "Reason",
    adjustBalance: "Adjust balance",
    adjustingBalance: "Adjusting balance...",
    balanceAdjusted: "Balance adjusted.",
    balanceAdjustFailed: "Failed to adjust balance.",
    balanceAfter: "Balance after",
    economyAuditNotice: "This action is audited.",
    positiveAmountHint: "Positive amount adds balance.",
    negativeAmountHint: "Negative amount removes balance.",
    quickPresets: "Quick presets",
  },
  et: {
    welcome: "Tere tulemast Balkonisse",
    title: "Balkon",
    subtitle: "Discordi boti juhtpaneel majanduse, striimerite ja OBS-i jaoks.",
    loginWithDiscord: "Logi sisse Discordiga",
    searching: "Otsi vahelehti...",
    marketOverviewSearchDescription: "Kapitalisatsioon ja ODM graafik",
    marketListingsSearchDescription: "Müügis olevad mängijate esemed",
    marketForbesSearchDescription: "Top 10 kasutajat ODM järgi",
    botShopSearchDescription: "Ost botipoest",
    inventorySearchDescription: "Sinu esemed, müük ja ülekanne",
    craftSearchDescription: "Retseptid ja esemete loomine",
    profileSearchDescription: "Konto ja Discordi profiil",
    loadingSession: "Sessiooni kontroll...",
    loadingInventory: "Laen inventari...",
    inventoryEmpty: "Inventar on tühi.",
    noRoles: "Rolle pole",
    discordId: "Discord ID",
    obtained: "Saadud",
    itemDetails: "Esme detailid",
    close: "Sulge",
    itemId: "Esme ID",
    templateId: "Malli ID",
    owner: "Omanik",
    originalOwner: "Algne omanik",
    rarity: "Haruldus",
    type: "Tüüp",
    tier: "Tase",
    botSellPrice: "Botile müügihind",
    noItemSelected: "Ese pole valitud.",
    selectItemHint: "Täisdetailide nägemiseks vali vasakult ese.",
    tabOverview: "Ülevaade",
    tabInventory: "Inventar",
    tabMarket: "Turg",
    tabBotShop: "Pood",
    tabCraft: "Craft",
    tabProfile: "Profiil",
    tabNotifications: "Teavitused",
    tabServers: "Serverid",
    tabStreamerStudio: "Striimija stuudio",
    navMain: "Peamine",
    navPersonal: "Isiklik",
    navEconomy: "Majandus",
    navObs: "Striimid",
    navServers: "Serverid",
    navAdmin: "Admin",
    myServers: "Minu serverid",
    serversComingSoon: "Varsti",
    serverManagementDescription: "Peagi saad siin valida Discordi serveri ning hallata majandust, liikmeid ja seadeid.",
    serversTitle: "Minu serverid",
    serversSubtitle: "Vali registreeritud Discordi server, et vaadata ülevaadet ja valmistada haldustööriistu.",
    serversEmpty: "Registreeritud servereid veel pole.",
    serversError: "Serverite laadimine ebaõnnestus.",
    serversRefresh: "Värskenda",
    openServer: "Ava",
    backToServers: "Serverite juurde",
    serverRoleOwner: "Omanik",
    serverRoleAdmin: "Admin",
    serverRoleMember: "Liige",
    serverRoleUnknown: "Teadmata",
    serverHomeGuild: "Koduserver",
    serverMembers: "Liikmed",
    serverStreamers: "Striimerid",
    serverItems: "Esemed",
    serverInventory: "Inventar",
    serverMarketListings: "Turu pakkumised",
    serverTabOverview: "Ülevaade",
    serverTabEconomy: "Majandus",
    serverTabMembers: "Liikmed",
    serverTabLogs: "Logid",
    serverTabSettings: "Seaded",
    serverSectionComingSoon: "Selle jaotise haldus ilmub siia peagi.",
    obsShop: "OBS pood",
    obsHistory: "OBS ajalugu",
    streamerStudioTitle: "Striimija stuudio",
    streamerStudioSubtitle: "Halda OBS stseene ja elementide paigutust brauserist.",
    streamerStudioRefresh: "Värskenda",
    streamerStudioEmpty: "Pole ligipääsetavaid striimijaid.",
    streamerStudioError: "Striimija stuudio laadimine ebaõnnestus.",
    streamerStudioOpenControl: "Ava kontroll",
    streamerStudioBack: "Tagasi",
    streamerStudioRoleOwner: "Omanik",
    streamerStudioRoleManager: "Haldur",
    streamerStudioRoleModerator: "Moderaator",
    streamerStudioRoleBotAdmin: "Bot admin",
    streamerStudioCanControl: "Saab juhtida",
    streamerStudioCanManage: "Saab hallata",
    streamerStudioAgentOnline: "OBS agent online",
    streamerStudioAgentOffline: "OBS agent offline",
    streamerStudioAgentNotConfigured: "OBS agent pole seadistatud",
    streamerStudioAgentVersionLabel: "Agendi versioon",
    streamerStudioRelayProtocolLabel: "Relay protocol versioon",
    streamerStudioCapabilitiesLabel: "Võimekused",
    streamerStudioObsStatusLabel: "OBS",
    streamerStudioObsConnected: "ühendatud",
    streamerStudioObsDisconnected: "ühendamata",
    streamerStudioObsVersionLabel: "OBS-i versioon",
    streamerStudioObsWebsocketVersionLabel: "obs-websocketi versioon",
    streamerStudioCapabilitiesUnknown: "OBS Agendi võimekused on teadmata. Kui laiendatud juhtimine ebaõnnestub, uuenda ja taaskäivita agent.",
    streamerStudioCapabilityUnsupported: "OBS Agent on aegunud või ei toeta seda käsku. Uuenda ja taaskäivita agent.",
    streamerStudioObsNotConnected: "OBS pole ühendatud. Ava OBS ja ühenda agent uuesti.",
    streamerStudioScenes: "Stseenid",
    streamerStudioLoadScenes: "Lae stseenid",
    streamerStudioRefreshScenes: "Värskenda stseene",
    streamerStudioRefreshItems: "Värskenda elemente",
    streamerStudioLoadingScenes: "Laen stseene...",
    streamerStudioLoadingItems: "Laen stseeni elemente...",
    streamerStudioSceneItems: "Stseeni elemendid",
    streamerStudioNoScenes: "Stseene pole",
    streamerStudioNoItems: "Elemente pole",
    streamerStudioSelectScene: "Vali stseen",
    streamerStudioPreview: "Eelvaade",
    streamerStudioInspector: "Inspektor",
    streamerStudioUnknownInput: "unknown",
    streamerStudioTypeGroup: "group",
    streamerStudioRecommended: "Soovitatud",
    streamerStudioEnabled: "Sees",
    streamerStudioDisabled: "Väljas",
    streamerStudioApplyTransform: "Rakenda OBS-is",
    streamerStudioResetTransform: "Lähtesta muudatused",
    streamerStudioUnsavedChanges: "Salvestamata muudatused on olemas",
    streamerStudioTransformApplied: "Asukoht rakendati",
    streamerStudioTransformApplyFailed: "Asukoha rakendamine ebaõnnestus",
    streamerStudioLayerControlsTitle: "Kiht",
    streamerStudioMoveLayerUp: "Liiguta üles",
    streamerStudioMoveLayerDown: "Liiguta alla",
    streamerStudioMoveLayerTop: "Kõige üles",
    streamerStudioMoveLayerBottom: "Kõige alla",
    streamerStudioLayerApplied: "Kihtide järjekord uuendatud",
    streamerStudioLayerApplyFailed: "Kihtide järjekorra muutmine ebaõnnestus",
    streamerStudioVisibilityControlsTitle: "Nähtavus",
    streamerStudioShowItem: "Näita",
    streamerStudioHideItem: "Peida",
    streamerStudioRemoveItem: "Eemalda",
    streamerStudioVisibilityApplied: "Nähtavus uuendatud",
    streamerStudioVisibilityApplyFailed: "Nähtavuse muutmine ebaõnnestus",
    streamerStudioRemoveApplied: "Element eemaldati stseenist",
    streamerStudioRemoveFailed: "Elemendi eemaldamine ebaõnnestus",
    streamerStudioRemoveConfirm: "Kas eemaldada element sellest OBS-stseenist?",
    streamerStudioRemoveHint: "Eemaldab elemendi ainult praegusest stseenist.",
    streamerStudioTransformX: "X",
    streamerStudioTransformY: "Y",
    streamerStudioTransformScaleX: "Skaala X",
    streamerStudioTransformScaleY: "Skaala Y",
    streamerStudioTransformRotation: "Pööramine",
    streamerStudioDragHint: "Lohista valitud elementi või muuda väärtusi käsitsi",
    streamerStudioLayerOrderHint: "Sama järjekord nagu OBS-is: ülemised elemendid renderduvad alumiste peale.",
    streamerStudioDirtyRefreshConfirm: "Sul on salvestamata muudatused. Kas värskendada elemendid ja need lähtestada?",
    streamerStudioForbiddenHint: "Sul pole õigust seda striimijat juhtida.",
    streamerStudioCreateSourceTitle: "Loo allikas",
    streamerStudioCreateTextTitle: "Tekst",
    streamerStudioCreateTextSubtitle: "Lisa tekstiallikas valitud OBS-stseeni.",
    streamerStudioCreateTextContent: "Tekst",
    streamerStudioCreateTextSourceName: "Allika nimi",
    streamerStudioCreateTextSourceNamePlaceholder: "Näiteks: Balkon Text",
    streamerStudioCreateTextButton: "Lisa tekst",
    streamerStudioCreateTextSuccess: "Tekstiallikas loodud",
    streamerStudioCreateTextFailed: "Tekstiallika loomine ebaõnnestus",
    streamerStudioCreateTextInvalid: "Sisesta kuni 500 märgi pikkune tekst.",
    streamerStudioCreateTextOpen: "Ava",
    streamerStudioCreateTextCollapse: "Ahenda",
    streamerStudioSourceSettingsTitle: "Allika seaded",
    streamerStudioSourceSettingsLoading: "Laeme allika seadeid...",
    streamerStudioSourceSettingsLoadFailed: "Allika seadete laadimine ebaõnnestus",
    streamerStudioTextSettingsTitle: "Tekst",
    streamerStudioTextSettingsContent: "Sisu",
    streamerStudioTextSettingsPlaceholder: "Sisesta allika uus tekst",
    streamerStudioTextSettingsUpdate: "Uuenda teksti",
    streamerStudioTextSettingsSuccess: "Tekstiallikas uuendatud",
    streamerStudioTextSettingsFailed: "Tekstiallika uuendamine ebaõnnestus",
    streamerStudioTextSettingsInvalid: "Sisesta 1 kuni 500 märki.",
    streamerStudioCreateBrowserTitle: "Browser URL",
    streamerStudioCreateBrowserSubtitle: "Lisa browser source URL-i kaudu valitud OBS-stseeni.",
    streamerStudioCreateBrowserUrl: "URL",
    streamerStudioCreateBrowserUrlPlaceholder: "https://example.com/widget",
    streamerStudioCreateBrowserWidth: "Laius",
    streamerStudioCreateBrowserHeight: "Kõrgus",
    streamerStudioCreateBrowserButton: "Lisa Browser",
    streamerStudioCreateBrowserSuccess: "Browser source loodud",
    streamerStudioCreateBrowserFailed: "Browser source loomine ebaõnnestus",
    streamerStudioCreateBrowserInvalid: "Sisesta korrektne http/https URL.",
    streamerStudioBrowserSettingsTitle: "Browser source",
    streamerStudioBrowserSettingsUrl: "URL",
    streamerStudioBrowserSettingsUrlPlaceholder: "https://example.com/widget",
    streamerStudioBrowserSettingsWidth: "Laius",
    streamerStudioBrowserSettingsHeight: "Kõrgus",
    streamerStudioBrowserSettingsUpdate: "Uuenda Browser",
    streamerStudioBrowserSettingsSuccess: "Browser source uuendatud",
    streamerStudioBrowserSettingsFailed: "Browser source uuendamine ebaõnnestus",
    streamerStudioBrowserSettingsInvalid: "Täida vähemalt üks väli ja kasuta korrektset http/https URL-i.",
    streamerStudioCreateSourceTypeText: "Tekst",
    streamerStudioCreateSourceTypeBrowser: "Browser",
    streamerStudioTrustedUsersTitle: "Usaldatud kasutajad",
    streamerStudioTrustedUsersSubtitle: "Lisa inimesed, kes saavad sinu OBS-stseeni tasuta juhtida.",
    streamerStudioTrustedUsersRefresh: "Värskenda",
    streamerStudioTrustedUsersOpen: "Ava",
    streamerStudioTrustedUsersCollapse: "Ahenda",
    streamerStudioTrustedUsersCount: "{count} usaldatud",
    streamerStudioTrustedUsersEmpty: "Usaldatud kasutajaid veel pole.",
    streamerStudioTrustedUsersDiscordId: "Discord ID",
    streamerStudioTrustedUsersRole: "Roll",
    streamerStudioTrustedUsersAdd: "Lisa",
    streamerStudioTrustedUsersRemove: "Eemalda",
    streamerStudioTrustedUsersModerator: "Moderaator",
    streamerStudioTrustedUsersManager: "Haldur",
    streamerStudioTrustedUsersAddSuccess: "Kasutaja lisatud",
    streamerStudioTrustedUsersRemoveSuccess: "Ligipääs eemaldatud",
    streamerStudioTrustedUsersLoadFailed: "Usaldatud kasutajate laadimine ebaõnnestus",
    streamerStudioTrustedUsersSaveFailed: "Ligipääsu salvestamine ebaõnnestus",
    streamerStudioTrustedUsersDeleteFailed: "Ligipääsu eemaldamine ebaõnnestus",
    streamerStudioTrustedUsersInvalidDiscordId: "Discord ID peab sisaldama ainult numbreid ja olema kuni 32 märki pikk.",
    streamerStudioTrustedUsersManagerHint: "Haldur saab stseeni juhtida ja usaldatud kasutajaid hallata.",
    streamerStudioAgentSetupTitle: "OBS Agenti seadistus",
    streamerStudioAgentSetupSubtitle: "Ühenda lokaalne Balkon OBS Agent, et juhtida stseene ja allikaid brauserist.",
    streamerStudioAgentSetupRefresh: "Värskenda staatust",
    streamerStudioAgentSetupConfigured: "Sidumine seadistatud",
    streamerStudioAgentSetupNotConfigured: "Sidumine puudub",
    streamerStudioAgentSetupReady: "Agent on valmis",
    streamerStudioAgentSetupOfflineHint: "OBS Agent on võrguühenduseta",
    streamerStudioAgentSetupObsDisconnectedHint: "OBS pole ühendatud. Ava OBS ja ühenda agent uuesti.",
    streamerStudioAgentSetupTokenPresent: "Token on salvestatud",
    streamerStudioAgentSetupTokenMissing: "Token puudub",
    streamerStudioAgentSetupLastSeen: "Viimati nähtud",
    streamerStudioAgentSetupUnknown: "Teadmata",
    streamerStudioAgentSetupTabStatus: "Staatus",
    streamerStudioAgentSetupTabSetup: "Seadistus",
    streamerStudioAgentSetupTabToken: "Token",
    streamerStudioAgentSetupTabManualBind: "Käsitsi sidumine",
    streamerStudioAgentSetupTabDanger: "Ohtlik",
    streamerStudioAgentSetupInstructionsTitle: "Kuidas agent ühendada",
    streamerStudioAgentSetupInstructionInstall: "1. Paigalda või ava Balkon OBS Agent striimija arvutis.",
    streamerStudioAgentSetupInstructionRelay: "2. Sisesta Relay URL.",
    streamerStudioAgentSetupInstructionAgentId: "3. Sisesta Agent ID.",
    streamerStudioAgentSetupInstructionAgentToken: "4. Sisesta Agent Token.",
    streamerStudioAgentSetupInstructionObs: "5. Sisesta agendis OBS WebSocket URL ja parool.",
    streamerStudioAgentSetupInstructionStart: "6. Käivita agent ja oota ühendust.",
    streamerStudioAgentSetupRelayUnavailable: "Backend ei avalda veel Relay URL-i. Kasuta oma deploy relay URL-i konfiguratsioonist.",
    streamerStudioAgentSetupRelayLabel: "Relay URL",
    streamerStudioAgentSetupAgentIdLabel: "Agent ID",
    streamerStudioAgentSetupTokenLabel: "Agent Token",
    streamerStudioAgentSetupCustomAgentId: "Kohandatud Agent ID",
    streamerStudioAgentSetupCustomAgentIdPlaceholder: "Jäta tühjaks automaatseks genereerimiseks",
    streamerStudioAgentSetupGenerateToken: "Genereeri / roteeri token",
    streamerStudioAgentSetupGenerating: "Tokeni genereerimine...",
    streamerStudioAgentSetupCopy: "Kopeeri",
    streamerStudioAgentSetupCopied: "Kopeeritud",
    streamerStudioAgentSetupCopyFailed: "Kopeerimine ebaõnnestus",
    streamerStudioAgentSetupOneTimeTitle: "Uus token",
    streamerStudioAgentSetupOneTimeWarning: "Kopeeri see token kohe. Seda enam ei näidata.",
    streamerStudioAgentSetupCopyNowWarning: "Kopeeri token kohe. Pärast selle vaate sulgemist seda enam ei näidata.",
    streamerStudioAgentSetupBindTitle: "Käsitsi sidumine",
    streamerStudioAgentSetupBindSubtitle: "Kasuta seda siis, kui sul on juba Agent ID ja Agent Token olemas.",
    streamerStudioAgentSetupBindButton: "Salvesta sidumine",
    streamerStudioAgentSetupBinding: "Salvestan...",
    streamerStudioAgentSetupBindSuccess: "Sidumine salvestatud",
    streamerStudioAgentSetupBindFailed: "Sidumise salvestamine ebaõnnestus",
    streamerStudioAgentSetupProvisionSuccess: "Uus token genereeritud",
    streamerStudioAgentSetupProvisionFailed: "Tokeni genereerimine ebaõnnestus",
    streamerStudioAgentSetupClear: "Eemalda sidumine",
    streamerStudioAgentSetupClearing: "Eemaldan...",
    streamerStudioAgentSetupClearSuccess: "Sidumine eemaldatud",
    streamerStudioAgentSetupClearFailed: "Sidumise eemaldamine ebaõnnestus",
    streamerStudioAgentSetupClearConfirm: "Kas eemaldada selle striimija praegune OBS Agenti sidumine?",
    streamerStudioAgentSetupClearWarning: "See eemaldab striimeri praeguse OBS Agenti sidumise. Pärast seda tuleb agent uuesti seadistada või uuesti siduda.",
    streamerStudioAgentSetupInvalidBind: "Sisesta nii Agent ID kui ka Agent Token.",
    configure: "Seadista",
    quickActions: "Kiirtoimingud",
    recentActivity: "Viimane tegevus",
    overviewNotLoaded: "Laadimata",
    overviewOpenInventory: "Ava inventar",
    overviewProfileHint: "Seadista koduserver ja avalik kirjeldus.",
    overviewRecentEmpty: "Hiljutist tegevust veel pole.",
    overviewLoadFailed: "Ülevaate laadimine ebaõnnestus.",
    overviewShowcaseEyebrow: "Vitrin",
    overviewShowcaseTitle: "Balkon vitriin",
    overviewShowcaseSubtitle: "Siia tuleb Balkon esemete, efektide ja sündmuste 3D-vitriin.",
    overviewModelSoon: "3D mudel tuleb varsti",
    profile: "Profiil",
    logout: "Logi välja",
    balance: "Saldo",
    odm: "ODM",
    ldm: "LDM",
    balanceLoadFailed: "Saldo laadimine ebaõnnestus.",
    buy: "Osta",
    buying: "Ostan...",
    amount: "Kogus",
    total: "Kokku",
    notEnoughBalance: "Ei piisa ODM.",
    purchaseSuccess: "Ostetud!",
    purchaseFailed: "Ostmine ebaõnnestus.",
    languages: "Keel",
    marketSoon: "Turu vaade lisatakse peagi.",
    marketLoading: "Laen turgu...",
    marketEmpty: "Turul pole veel pakkumisi.",
    marketError: "Turu laadimine ebaõnnestus.",
    marketPrice: "Hind",
    marketSeller: "Müüja",
    marketListingId: "Pakkumine",
    marketInventoryItemId: "Inventari ID",
    marketOverview: "Ülevaade",
    marketListings: "Esemed",
    marketForbes: "Balkon Forbes",
    marketSubtabLabel: "Turu alamsakid",
    marketCapitalization: "Turu kapitalisatsioon",
    totalOdm: "Kokku ODM",
    totalLdm: "Kokku LDM",
    marketMembers: "Liikmed",
    changeSinceYesterday: "võrreldes eelmise päevaga",
    previousDay: "Eelmine päev",
    noPreviousData: "Eelmise päeva andmed puuduvad.",
    capitalizationLoading: "Laen turu kapitalisatsiooni...",
    capitalizationEmpty: "Graafiku jaoks pole piisavalt andmeid.",
    capitalizationError: "Turu kapitalisatsiooni laadimine ebaõnnestus.",
    marketLiveToday: "Tänase päeva reaalajas hetkeseis",
    lastDays: "Viimased päevad",
    listings: "Pakkumised",
    marketRefresh: "Värskenda",
    sellToBot: "Müü botile",
    listOnMarket: "Lisa turule",
    useService: "Kasuta teenust",
    selectStreamer: "Vali striimer",
    marketBuyListing: "Osta pakkumine",
    updateListingPrice: "Muuda hinda",
    cancelListing: "Tühista pakkumine",
    listingOfferPriceLabel: "Hind (ODM)",
    listingOfferPricePlaceholder: "Hind ODM-is",
    confirmSellToBotTitle: "Müük botile",
    confirmSellToBotMessage:
      "Müüa see ese botile? Lõpliku summa ja tingimused kinnitab server müügil.",
    confirmMarketPurchaseTitle: "Ost turult",
    confirmMarketPurchaseMessage:
      "Osta see pakkumine? ODM mahakandmine ja ese kinnitab server.",
    confirmCancelListingTitle: "Tühista pakkumine",
    confirmCancelListingMessage: "Kas võtta oma pakkumine turult maha? Ese tagasi — kontrollib server.",
    invalidPositiveFinitePrice: "Sisesta positiivne lõplik hind.",
    sellingToBot: "Müüan botile...",
    listingOnMarket: "Lisan pakkumise...",
    usingService: "Kasutan teenust...",
    usingServiceLoadingTargets: "Laen striimereid...",
    marketBuyingListing: "Ostan...",
    updatingMarketPrice: "Uuendan hinda...",
    cancellingMarketListing: "Tühistan...",
    inventoryAlreadyListedOnMarket: "Juba turul",
    noAvailableStreamers: "Saadaval striimereid pole.",
    marketSellBotSuccessReceived: "Müüdud. Saadud: {received} ODM.",
    marketSellBotSuccess: "Ese müüdi botile.",
    marketListSuccess: "Pakkumine loodud.",
    marketListToast: "Pakkumine loodud: {itemName} hinnaga {price} ODM",
    inventoryServiceUseSuccess: "Teenus kasutatud.",
    inventoryServiceUseSuccessConsumed: "Teenus kasutatud, ese kulutati.",
    inventoryServiceUseFailed: "Teenuse kasutamine ebaõnnestus.",
    marketBuySuccess: "Ost õnnestus.",
    marketUpdatePriceSuccess: "Hind uuendatud.",
    marketCancelSuccess: "Pakkumine tühistatud.",
    marketMutationFailed: "Tegevus ebaõnnestus.",
    toastCloseLabel: "Sulge teavitus",
    expandItemActions: "Tegevused",
    collapseItemActions: "Peida tegevused",
    marketForbesDescription: "Top 10 kasutajat ODM järgi",
    marketForbesLoading: "Laen Balkon Forbes edetabelit...",
    marketForbesEmpty: "Edetabeli andmeid veel pole.",
    marketForbesError: "Balkon Forbes laadimine ebaõnnestus.",
    marketForbesRefresh: "Värskenda",
    rank: "Koht",
    fromGuild: "Pärit",
    hidden: "peidetud",
    streamerModeHidden: "Striimija reziimis peidetud",
    noHomeGuild: "Koduserver puudub",
    noDescription: "Avalik kirjeldus puudub.",
    topByOdm: "Top 10 kasutajat ODM järgi",
    botShopLoading: "Laen botipoodi...",
    botShopEmpty: "Botipood on praegu tühi.",
    botShopError: "Botipoe laadimine ebaõnnestus.",
    botShopPrice: "Hind",
    botShopRefresh: "Värskenda",
    shopOverview: "Ülevaade",
    shopItems: "Esemed",
    shopCases: "Kastid",
    shopObs: "OBS",
    shopCasesSoon: "Kastid tulevad peagi.",
    shopObsStreamers: "OBS striimerid",
    shopObsEmpty: "Striimereid pole registreeritud.",
    shopObsLoading: "Laen striimereid...",
    shopObsError: "OBS striimerite laadimine ebaõnnestus.",
    twitch: "Twitch",
    openStreamer: "Ava",
    backToStreamers: "Tagasi striimerite juurde",
    streamerPrimary: "Põhi",
    agentConnected: "Agent ühendatud",
    agentOffline: "Agent offline",
    agentOfflineRecently: "Agent offline · viimati nähtud",
    agentNotConfigured: "Agent seadistamata",
    streamLive: "Otse-eeter",
    streamOffline: "Offline",
    streamUnknown: "Teadmata",
    media: "Meedia",
    showImageFiveSeconds: "Näita pilti 5 sekundit",
    showGifFiveSeconds: "Näita GIF-i 5 sekundit",
    durationSeconds: "Kestus, sek",
    purchaseSoon: "Varsti",
    obsMediaPurchaseSuccess: "Efekt saadetud.",
    obsMediaPurchaseFailed: "OBS efekti saatmine ebaõnnestus.",
    effectSent: "Efekt saadetud",
    purchaseUnavailable: "Pole saadaval",
    obsMediaDescription: "OBS stseenide meediaefektide ostmine.",
    obsMediaHistory: "Ajalugu",
    obsMediaHistoryEmpty: "OBS meediaoste veel pole.",
    obsMediaHistoryError: "OBS meedia ajaloo laadimine ebaõnnestus.",
    obsMediaHistoryLoading: "Laen OBS meedia ajalugu...",
    obsActionStatusPending: "Ootel",
    obsActionStatusSent: "Saadetud",
    obsActionStatusFailed: "Ebaõnnestus",
    obsActionStatusRefunded: "Tagastatud",
    refunded: "Tagastus",
    commandId: "Käsu ID",
    errorMessage: "Viga",
    craftLoading: "Laen crafti retsepte...",
    craftEmpty: "Crafti retsepte veel pole.",
    craftError: "Crafti retseptide laadimine ebaõnnestus.",
    craftRefresh: "Värskenda",
    craftResult: "Tulemus",
    craftIngredients: "Koostisosad",
    craftRecipeId: "Retsept",
    craftResultItemId: "Tulemuse ID",
    profileSection: "Kasutaja profiil",
    profileSettings: "Avaliku profiili seaded",
    streamerMode: "Striimeri reziim",
    homeGuild: "Koduserver",
    selectHomeGuild: "Vali koduserver",
    guildNotSelected: "Server pole valitud",
    discordProfileNotCached: "Discordi profiil pole vahemallu salvestatud",
    publicDescription: "Avalik kirjeldus",
    publicDescriptionPlaceholder: "Kirjelda ennast või lisa promo...",
    publicDescriptionPublicWarning: "Kirjeldus on avalik. Modereerimine lisatakse hiljem.",
    saveProfile: "Salvesta profiil",
    profileSaved: "Profiil salvestatud.",
    profileSaveFailed: "Profiili salvestamine ebaõnnestus.",
    apiReachFailedHint: "API-ga ei saanud uhendust. Kontrolli, et API tootab ja CORS lubab PATCH-i.",
    charactersLeft: "Märke jäänud",
    notSelected: "Pole valitud",
    tradeableYes: "Vahetatav",
    tradeableNo: "Ei ole vahetatav",
    sellableYes: "Müüdav",
    sellableNo: "Ei ole müüdav",
    botSell: "Botile müük",
    unknownDate: "Teadmata",
    checking: "Andmete kontroll...",
    previous: "Eelmine",
    next: "Järgmine",
    page: "Leht",
    status: "Status",
    statusOnline: "Töötab",
    statusOffline: "Ei tööta",
    statusDevelopment: "Arenduses",
    inventoryFilterAll: "Kõik",
    inventoryFilterMaterials: "Materjalid",
    inventoryFilterSellable: "Müüdavad",
    inventoryFilterTradeable: "Vahetatavad",
    inventoryFilterLabel: "Inventari filter",
    inventorySearchPlaceholder: "Otsi esemeid...",
    inventorySearchNoResults: "Esemeid ei leitud.",
    inventorySearchClearAria: "Tühjenda otsing",
    itemsWord: "eset",
    noSellableItems: "Müüdavaid esemeid veel pole.",
    noTradeableItems: "Vahetatavaid esemeid veel pole.",
    noMaterialsItems: "Materjale veel pole.",
    notifications: "Teavitused",
    notificationEmpty: "Teavitusi veel pole.",
    notificationLoading: "Laen teavitusi...",
    notificationError: "Teavituste laadimine ebaõnnestus.",
    notificationUnread: "Lugemata",
    obsNotificationTitle: "OBS efekt saadetud",
    obsNotificationBody: "Efekt saadeti striimerile.",
    obsNotificationEffectPrefix: "Efekt",
    obsNotificationSentTo: "saadeti striimerile",
    balanceUpdated: "Saldo uuendatud",
    markRead: "Märgi loetuks",
    markAllRead: "Märgi kõik loetuks",
    viewAll: "Ava kõik",
    unreadOnly: "Ainult lugemata",
    allNotifications: "Kõik teavitused",
    notificationRead: "Loetud",
    notificationOpenLink: "Ava link",
    notificationRefresh: "Värskenda",
    notificationBellAria: "Ava teavitused",
    noNotificationsYet: "Teavitusi veel pole.",
    adminMode: "Režiim",
    adminModeUser: "Kasutaja",
    adminModeAdmin: "Admin",
    adminTabDashboard: "Dashboard",
    adminTabServers: "Serverid",
    adminTabLogs: "Logid",
    adminTabObs: "OBS",
    adminTabItems: "Esemed",
    adminEconomy: "Valuuta",
    adminTabMessage: "Teavitus",
    adminStatsLoading: "Laen admin-statistikat...",
    adminStatsError: "Admin-statistika laadimine ebaõnnestus.",
    adminStatsEmpty: "Admin-statistika puudub.",
    retry: "Proovi uuesti",
    adminCountGuilds: "Guildid",
    adminCountMembers: "Liikmed",
    adminCountItems: "Esemed",
    adminCountInventory: "Inventar",
    adminCountMarket: "Turg",
    adminCountStore: "Pood",
    adminCountRecipes: "Retseptid",
    adminCountStreamers: "Striimerid",
    adminCountSettings: "Seaded",
    adminCountActions: "Tegevused",
    adminLogsEmpty: "Bootstrap-logisid veel pole.",
    statusOk: "OK",
    statusError: "Viga",
    source: "Allikas",
    updated: "Uuendatud",
    channelsSynced: "Kanalid sünk",
    rolesSynced: "Rollid sünk",
    messageLabel: "Sõnum",
    adminObsEmpty: "OBS seaded puuduvad.",
    adminObsMediaActions: "OBS Media Actions",
    actionBuyer: "Ostja",
    actionStreamer: "Striimer",
    actionProduct: "Toode",
    actionStatus: "Staatus",
    allStatuses: "Kõik staatused",
    contributors: "Contributors",
    none: "Puudub",
    adminServersSoon: "Serverite sektsioon on arenduses. Siia tulevad guildide haldus, juurdepääsud ja bootstrap kontrollid.",
    adminItemsSoon: "Esemete sektsioon on arenduses. Siia tulevad kataloogi haldus ja economy kontroll.",
    adminItemsTitle: "Kataloogi haldus",
    adminItemsRefresh: "Värskenda",
    adminItemsLoading: "Laen esemeid...",
    adminItemsEmpty: "Esemeid ei leitud.",
    adminItemsLoadError: "Esemete kataloogi laadimine ebaõnnestus.",
    adminItemsSaveError: "Esme salvestamine ebaõnnestus.",
    adminItemsDeleteError: "Esme kustutamine ebaõnnestus.",
    adminItemsCreated: "Ese loodud.",
    adminItemsUpdated: "Ese uuendatud.",
    adminItemsDeleted: "Ese kustutatud.",
    adminItemsName: "Nimi",
    adminItemsDescription: "Kirjeldus",
    adminItemsType: "Tüüp",
    adminItemsRarity: "Haruldus",
    adminItemsEmoji: "Emoji",
    adminItemsImageUrl: "Pildi URL",
    adminItemsBotSellPrice: "Botile müügihind",
    adminItemsTradeable: "Vahetatav",
    adminItemsSearchType: "Otsi tüüpi",
    adminItemsSearchRarity: "Otsi haruldust",
    adminItemsNoOptions: "Vasteid pole",
    adminItemsCreate: "Loo",
    adminItemsUpdate: "Salvesta",
    adminItemsCancelEdit: "Tühista",
    adminItemsEdit: "Muuda",
    adminItemsDelete: "Kustuta",
    adminItemsSearchPlaceholder: "Otsi nime, tüübi või harulduse järgi...",
    adminItemsValidationRequired: "Täida kohustuslikud väljad: nimi, kirjeldus, tüüp ja haruldus.",
    adminItemsValidationPrice: "Botile müügihind peab olema arv, mis on 0 või suurem.",
    adminItemsDeleteConfirmTitle: "Kustuta ese",
    adminItemsDeleteConfirmText: "Kas soovid kindlasti kustutada:",
    adminItemsDeleteConfirmAction: "Kinnita kustutamine",
    adminTabBotShop: "Pood",
    adminBroadcast: "Teavitus",
    adminBroadcastTitle: "Pealkiri",
    adminBroadcastBody: "Sisu",
    adminBroadcastImageUrl: "Pildi URL",
    adminBroadcastLinkUrl: "Lingi URL",
    adminBroadcastSeverity: "Olulisus",
    adminBroadcastPreview: "Eelvaade",
    adminBroadcastSend: "Saada",
    adminBroadcastSending: "Saadan...",
    adminBroadcastSent: "Teavitus saadetud. Saajaid:",
    adminBroadcastFailed: "Teavituse saatmine ebaõnnestus.",
    severityInfo: "Info",
    severitySuccess: "Edu",
    severityWarning: "Hoiatus",
    severityDanger: "Tähtis",
    adminBotShopTitle: "Poe haldus",
    adminBotShopRefresh: "Värskenda",
    adminBotShopLoading: "Laen pood...",
    adminBotShopEmpty: "Pood on tühi.",
    adminBotShopLoadError: "Poe laadimine ebaõnnestus.",
    adminBotShopSaveError: "Kirje salvestamine ebaõnnestus.",
    adminBotShopDeleteError: "Kirje kustutamine ebaõnnestus.",
    adminBotShopSaved: "Kirje salvestatud.",
    adminBotShopDeleted: "Kirje kustutatud.",
    adminBotShopAddTitle: "Lisa / uuenda kirje",
    adminBotShopSelectItem: "Vali ese",
    adminBotShopSearchItem: "Otsi eset...",
    adminBotShopNoResults: "Vasteid pole",
    adminBotShopPrice: "Hind",
    adminBotShopSave: "Salvesta",
    adminBotShopSelectedItem: "Valitud ese",
    adminBotShopClearItem: "Tühista",
    adminBotShopValidationItem: "Palun vali ese nimekirjast.",
    adminBotShopValidationInvalidId: "Valitud esemel on vigane identifikaator.",
    adminBotShopValidationPrice: "Hind peab olema arv, mis on suurem kui 0.",
    adminBotShopDeleteConfirmTitle: "Kustuta kirje",
    adminBotShopDeleteConfirmText: "Kas soovid kindlasti kustutada kirje esemele:",
    adminBotShopDeleteConfirmAction: "Kinnita kustutamine",
    adminBotShopCancel: "Tühista",
    adminBotShopDelete: "Kustuta",
    adminBotShopListingId: "Kirje",
    adminEconomyTitle: "Saldo korrigeerimine",
    adminEconomyDescription: "Anna või eemalda ODM/LDM testimiseks, preemiateks ja kompensatsiooniks.",
    targetDiscordId: "Kasutaja Discord ID",
    currency: "Valuuta",
    adminEconomyReason: "Põhjus",
    adjustBalance: "Muuda saldot",
    adjustingBalance: "Muudan saldot...",
    balanceAdjusted: "Saldo uuendatud.",
    balanceAdjustFailed: "Saldo muutmine ebaõnnestus.",
    balanceAfter: "Saldo pärast",
    economyAuditNotice: "See tegevus logitakse.",
    positiveAmountHint: "Positiivne summa lisab saldot.",
    negativeAmountHint: "Negatiivne summa eemaldab saldot.",
    quickPresets: "Kiirvalikud",
  },
} as const;

export type DashboardText = (typeof DASHBOARD_TEXT)[LanguageCode];

export function formatDashboardDate(value: string | Date | null | undefined, locale: string, unknownDate: string): string {
  if (value === null || value === undefined) {
    return unknownDate;
  }

  const date = new Date(String(value));
  if (Number.isNaN(date.getTime())) {
    return unknownDate;
  }

  return new Intl.DateTimeFormat(locale, {
    year: "numeric",
    month: "short",
    day: "2-digit",
  }).format(date);
}
